function RSL_SpawnPoints_NonRes_Louisville_A()
    local points = {
        { worldX=42, worldY=14, posX=56, posY=170, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=14, posX=27, posY=149, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=14, posX=40, posY=134, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=14, posX=38, posY=121, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=14, posX=288, posY=214, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=14, posX=287, posY=181, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=14, posX=166, posY=46, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=14, posX=167, posY=74, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=14, posX=189, posY=125, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=14, posX=195, posY=104, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=14, posX=170, posY=99, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=11, posX=29, posY=191, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=11, posX=25, posY=201, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=11, posX=33, posY=220, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=11, posX=4, posY=260, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=11, posX=3, posY=259, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=11, posX=31, posY=249, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=11, posX=4, posY=248, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=281, posY=210, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=260, posY=235, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=273, posY=230, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=261, posY=216, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=252, posY=217, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=289, posY=231, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=281, posY=204, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=283, posY=213, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=296, posY=286, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=282, posY=270, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=281, posY=278, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=248, posY=285, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=262, posY=19, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=257, posY=27, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=252, posY=17, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=257, posY=13, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=254, posY=58, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=246, posY=60, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=247, posY=43, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=244, posY=45, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=292, posY=46, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=282, posY=39, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=292, posY=30, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=297, posY=40, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=17, posY=29, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=27, posY=26, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=21, posY=15, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=4, posY=17, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=6, posY=16, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=30, posY=67, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=28, posY=92, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=31, posY=100, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=25, posY=104, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=13, posY=105, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=18, posY=107, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=250, posY=89, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=271, posY=101, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=264, posY=98, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=263, posY=104, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=10, posY=191, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=13, posY=133, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=26, posY=153, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=255, posY=168, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=248, posY=200, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=252, posY=199, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=250, posY=199, posZ=2, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=136, posY=234, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=135, posY=184, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=11, posX=244, posY=232, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=11, posX=252, posY=256, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=11, posX=248, posY=228, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=28, posY=234, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=11, posY=243, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=7, posY=238, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=18, posY=239, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=80, posY=8, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=86, posY=16, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=75, posY=26, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=76, posY=36, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=71, posY=66, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=78, posY=109, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=86, posY=93, posZ=3, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=77, posY=118, posZ=3, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=117, posY=73, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=12, posX=71, posY=91, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=126, posY=228, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=7, posY=267, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=16, posY=251, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=54, posY=248, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=74, posY=250, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=43, posY=252, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=68, posY=261, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=122, posY=25, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=112, posY=56, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=124, posY=50, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=137, posY=107, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=154, posY=127, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=114, posY=146, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=112, posY=139, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=117, posY=130, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=111, posY=122, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=131, posY=126, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=125, posY=80, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=144, posY=68, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=75, posY=5, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=72, posY=37, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=34, posY=95, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=8, posX=252, posY=263, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=15, posY=240, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=29, posY=234, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=33, posY=219, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=14, posY=136, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=21, posY=34, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=9, posY=11, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=31, posY=52, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=90, posY=210, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=106, posY=213, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=131, posY=235, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=8, posX=275, posY=144, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=8, posX=274, posY=130, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=8, posX=4, posY=148, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=8, posX=20, posY=145, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=8, posX=25, posY=146, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=8, posX=68, posY=133, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=27, posY=251, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=72, posY=265, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=64, posY=255, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=155, posY=273, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=157, posY=250, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=135, posY=170, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=143, posY=167, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=65, posY=182, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=64, posY=192, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=80, posY=132, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=27, posY=147, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=27, posY=176, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=36, posY=143, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=26, posY=108, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=60, posY=77, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=36, posY=19, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=142, posY=36, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=82, posY=34, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=106, posY=46, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=175, posY=44, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=160, posY=13, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=158, posY=283, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=130, posY=256, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=137, posY=281, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=182, posY=281, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=176, posY=271, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=185, posY=261, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=39, posY=264, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=13, posY=250, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=61, posY=254, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=38, posY=264, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=42, posY=250, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=68, posY=240, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=18, posY=124, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=124, posY=120, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=109, posY=118, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=118, posY=80, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=140, posY=42, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=151, posY=35, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=132, posY=61, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=179, posY=122, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=171, posY=140, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=182, posY=166, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=192, posY=178, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=187, posY=196, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=176, posY=209, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=189, posY=256, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=163, posY=277, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=172, posY=255, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=137, posY=248, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=146, posY=273, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=113, posY=273, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=65, posY=232, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=59, posY=225, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=51, posY=263, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=64, posY=244, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=256, posY=214, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=258, posY=213, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=178, posY=202, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=141, posY=210, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=41, posY=208, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=32, posY=188, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=83, posY=105, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=93, posY=121, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=84, posY=103, posZ=2, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=92, posY=99, posZ=3, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=87, posY=105, posZ=4, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=117, posY=120, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=34, posY=18, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=84, posY=268, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=71, posY=235, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=81, posY=253, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=70, posY=23, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=74, posY=226, posZ=2, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=68, posY=236, posZ=3, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=109, posY=126, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=118, posY=75, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=119, posY=59, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=74, posY=54, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=203, posY=72, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=185, posY=57, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=223, posY=119, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=173, posY=133, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=204, posY=141, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=218, posY=149, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=232, posY=151, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=226, posY=173, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=201, posY=182, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=170, posY=200, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=187, posY=197, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=167, posY=254, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=184, posY=255, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=268, posY=74, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=231, posY=81, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=246, posY=68, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=173, posY=124, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=179, posY=93, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=173, posY=126, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=233, posY=127, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=230, posY=115, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=261, posY=117, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=70, posY=140, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=77, posY=141, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=68, posY=126, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=82, posY=131, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=71, posY=111, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=77, posY=96, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=72, posY=86, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=76, posY=63, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=73, posY=54, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=70, posY=40, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=77, posY=27, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=77, posY=19, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=79, posY=8, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=74, posY=283, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=75, posY=268, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=68, posY=230, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=70, posY=215, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=25, posY=238, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=269, posY=250, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=264, posY=243, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=274, posY=247, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=264, posY=181, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=278, posY=132, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=288, posY=138, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=283, posY=160, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=11, posY=78, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=30, posY=81, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=32, posY=68, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=4, posY=46, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=17, posY=47, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=21, posY=51, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=50, posY=48, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=62, posY=62, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=82, posY=136, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=71, posY=115, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=101, posY=137, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=23, posY=110, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=29, posY=106, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=23, posY=115, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=28, posY=117, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=19, posY=129, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=4, posY=131, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=13, posY=107, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=14, posY=179, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=28, posY=165, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=51, posY=167, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=64, posY=170, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=73, posY=174, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=77, posY=182, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=76, posY=195, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=128, posY=174, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=107, posY=187, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=118, posY=234, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=133, posY=224, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=139, posY=220, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=121, posY=211, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=120, posY=265, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=114, posY=278, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=107, posY=11, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=111, posY=33, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=111, posY=56, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=106, posY=59, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=167, posY=116, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=105, posY=112, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=180, posY=119, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=248, posY=139, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=220, posY=124, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=146, posY=168, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=166, posY=187, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=108, posY=125, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=183, posY=171, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=192, posY=185, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=189, posY=194, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=182, posY=222, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=186, posY=234, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=171, posY=231, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=223, posY=228, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=245, posY=276, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=246, posY=275, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=275, posY=275, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=272, posY=268, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=282, posY=241, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=263, posY=216, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=271, posY=228, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=263, posY=204, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=270, posY=184, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=265, posY=180, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=279, posY=171, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=226, posY=166, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=237, posY=167, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=272, posY=134, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=276, posY=128, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=277, posY=120, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=273, posY=123, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=269, posY=103, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=271, posY=109, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=252, posY=16, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=272, posY=53, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=261, posY=20, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=278, posY=20, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=268, posY=59, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=218, posY=28, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=217, posY=34, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=173, posY=30, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=162, posY=47, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=175, posY=30, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=141, posY=278, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=154, posY=280, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=176, posY=278, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=184, posY=269, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=194, posY=290, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=184, posY=248, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=187, posY=237, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=228, posY=249, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=213, posY=237, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=226, posY=283, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=238, posY=275, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=233, posY=280, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=268, posY=261, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=251, posY=270, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=266, posY=238, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=270, posY=251, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=258, posY=249, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=261, posY=188, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=248, posY=176, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=225, posY=202, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=242, posY=179, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=244, posY=176, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=185, posY=180, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=186, posY=163, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=150, posY=190, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=149, posY=174, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=119, posY=118, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=142, posY=136, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=143, posY=107, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=166, posY=136, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=179, posY=128, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=163, posY=57, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=154, posY=77, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=3, posX=256, posY=214, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=29, posY=257, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=44, posY=250, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=65, posY=257, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=59, posY=252, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=59, posY=243, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=99, posY=245, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=119, posY=242, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=125, posY=256, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=126, posY=235, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=160, posY=234, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=182, posY=230, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=191, posY=257, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=170, posY=235, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=248, posY=16, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=229, posY=7, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=220, posY=8, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=213, posY=6, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=194, posY=17, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=183, posY=5, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=156, posY=4, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=145, posY=291, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=137, posY=288, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=122, posY=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=112, posY=286, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=103, posY=286, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=105, posY=8, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=96, posY=10, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=72, posY=8, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=70, posY=292, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=56, posY=289, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=46, posY=294, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=41, posY=287, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=3, posX=32, posY=292, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=58, posY=10, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=37, posY=14, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=27, posY=5, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=244, posY=53, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=240, posY=55, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=221, posY=60, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=255, posY=77, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=280, posY=75, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=261, posY=81, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=267, posY=96, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=272, posY=110, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=274, posY=125, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=244, posY=134, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=241, posY=119, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=237, posY=129, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=225, posY=120, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=29, posY=73, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=18, posY=117, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=63, posY=120, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=30, posY=115, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=18, posY=125, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=60, posY=97, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=51, posY=95, posZ=4, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=20, posY=97, posZ=5, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=61, posY=167, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=61, posY=200, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=62, posY=187, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=54, posY=236, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=71, posY=244, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=62, posY=247, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=37, posY=163, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=22, posY=163, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=23, posY=173, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=14, posY=202, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=26, posY=217, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=26, posY=237, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=25, posY=253, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=58, posY=255, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=28, posY=254, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=70, posY=129, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=56, posY=137, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=68, posY=134, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=60, posY=122, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=65, posY=105, posZ=4, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=67, posY=114, posZ=5, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=70, posY=127, posZ=9, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=39, posY=136, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=33, posY=141, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=38, posY=134, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=35, posY=127, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=46, posY=141, posZ=5, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=46, posY=133, posZ=6, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=20, posY=130, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=24, posY=68, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=33, posY=71, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=44, posY=185, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=44, posY=188, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=19, posY=187, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=50, posY=188, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=24, posY=268, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=27, posY=208, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=34, posY=224, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=59, posY=50, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=53, posY=132, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=40, posY=114, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=17, posY=70, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=21, posY=82, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=16, posY=95, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=21, posY=99, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=15, posY=107, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=274, posY=20, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=268, posY=39, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=281, posY=37, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=262, posY=70, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=266, posY=77, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=272, posY=112, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=279, posY=138, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=261, posY=132, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=21, posY=230, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=44, posY=185, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=15, posY=198, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=44, posY=227, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=27, posY=230, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=30, posY=169, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=74, posY=268, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=27, posY=283, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=16, posY=285, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=28, posY=258, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=268, posY=193, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=281, posY=190, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=275, posY=204, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=274, posY=219, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=270, posY=224, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=277, posY=235, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=280, posY=198, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=223, posY=179, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=232, posY=174, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=234, posY=207, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=218, posY=203, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=271, posY=255, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=276, posY=275, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=276, posY=284, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=266, posY=288, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=267, posY=274, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=271, posY=14, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=257, posY=14, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=250, posY=16, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=261, posY=207, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=260, posY=226, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=8, posX=272, posY=8, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=8, posX=247, posY=18, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=8, posX=288, posY=144, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=8, posX=248, posY=195, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=8, posX=232, posY=185, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=161, posY=242, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=278, posY=158, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=269, posY=138, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=261, posY=138, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
    }
    return points
end
