function RSL_SpawnPoints_Residential_B()
    local points = {
        { worldX=44, worldY=7, posX=280, posY=60, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=145, posY=101, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=212, posY=148, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=171, posY=127, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=22, posY=160, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=283, posY=215, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=242, posY=139, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=163, posY=228, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=129, posY=80, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=88, posY=132, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=95, posY=18, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=98, posY=260, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=132, posY=232, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=104, posY=214, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=75, posY=186, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=50, posY=170, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=28, posY=190, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=19, posY=259, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=167, posY=114, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=196, posY=146, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=91, posY=222, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=114, posY=6, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=148, posY=252, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=46, posY=110, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=83, posY=171, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=177, posY=28, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=141, posY=219, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=54, posY=254, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=80, posY=295, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=78, posY=20, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=182, posY=56, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=242, posY=115, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=155, posY=28, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=185, posY=7, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=115, posY=56, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=125, posY=263, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=125, posY=245, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=116, posY=270, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=114, posY=244, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=164, posY=194, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=179, posY=228, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=222, posY=269, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=208, posY=13, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=282, posY=120, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=256, posY=86, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=253, posY=35, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=211, posY=78, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=177, posY=55, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=156, posY=21, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=180, posY=23, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=181, posY=57, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=181, posY=32, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=116, posY=116, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=120, posY=70, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=73, posY=100, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=69, posY=77, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=80, posY=22, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=121, posY=22, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=100, posY=21, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=117, posY=21, posZ=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=38, posY=15, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=13, posY=45, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=41, posY=35, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=16, posY=15, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=41, posY=105, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=43, posY=136, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=43, posY=136, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=267, posY=23, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=236, posY=22, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=241, posY=47, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=286, posY=49, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=170, posY=24, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=204, posY=35, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=197, posY=13, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=173, posY=37, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=199, posY=19, posZ=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=194, posY=17, posZ=6, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=131, posY=28, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=137, posY=12, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=136, posY=37, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=99, posY=61, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=96, posY=44, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=97, posY=16, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=184, posY=244, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=228, posY=284, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=265, posY=243, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=25, posY=287, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=42, posY=195, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=72, posY=244, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=276, posY=240, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=281, posY=233, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=266, posY=205, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=279, posY=201, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=263, posY=211, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=265, posY=168, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=279, posY=182, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=208, posY=89, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=264, posY=71, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=10, posY=57, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=89, posY=126, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=3, posY=240, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=243, posY=83, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=171, posY=117, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=149, posY=151, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=64, posY=250, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=145, posY=116, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=100, posY=122, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=174, posY=66, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=150, posY=27, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=6, posX=91, posY=49, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=92, posY=231, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=177, posY=195, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=221, posY=204, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=254, posY=179, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=94, posY=125, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=270, posY=130, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=264, posY=119, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=282, posY=101, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=265, posY=67, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=280, posY=70, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=276, posY=74, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=213, posY=10, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=220, posY=17, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=213, posY=16, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=214, posY=36, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=213, posY=66, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=212, posY=92, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=241, posY=114, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=228, posY=113, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=244, posY=127, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=230, posY=117, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=227, posY=130, posZ=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=207, posY=114, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=216, posY=113, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=218, posY=121, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=208, posY=121, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=208, posY=115, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=216, posY=113, posZ=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=282, posY=36, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=214, posY=26, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=243, posY=244, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=224, posY=267, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=281, posY=269, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=214, posY=243, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=122, posY=283, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=127, posY=268, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=109, posY=284, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=110, posY=268, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=127, posY=277, posZ=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=214, posY=265, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=212, posY=261, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=168, posY=33, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=199, posY=47, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=162, posY=11, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=202, posY=20, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=144, posY=16, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=186, posY=13, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=190, posY=13, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=113, posY=8, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=112, posY=18, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=104, posY=16, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=106, posY=8, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=112, posY=8, posZ=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=112, posY=18, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=86, posY=8, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=75, posY=8, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=78, posY=20, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=87, posY=8, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=75, posY=4, posZ=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=38, posY=5, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=47, posY=19, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=34, posY=19, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=35, posY=4, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=52, posY=4, posZ=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=281, posY=34, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=288, posY=53, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=287, posY=57, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=280, posY=85, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=283, posY=82, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=280, posY=92, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=67, posY=87, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=59, posY=75, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=44, posY=74, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=39, posY=74, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=24, posY=78, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=31, posY=75, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=9, posY=83, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=141, posY=231, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=119, posY=202, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=108, posY=230, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=105, posY=202, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=143, posY=224, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=107, posY=203, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=105, posY=238, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=136, posY=247, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=37, posY=254, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=48, posY=278, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=44, posY=38, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=106, posY=83, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=17, posY=59, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=22, posY=238, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=187, posY=262, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=172, posY=284, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=186, posY=247, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=232, posY=15, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=257, posY=33, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=279, posY=15, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=259, posY=38, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=226, posY=31, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=231, posY=14, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=206, posY=32, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=268, posY=20, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=17, posY=31, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=33, posY=14, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=36, posY=34, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=21, posY=29, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=22, posY=22, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=40, posY=14, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=25, posY=89, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=11, posY=70, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=19, posY=92, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=19, posY=137, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=20, posY=155, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=11, posY=124, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=48, worldY=10, posX=180, posY=38, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=48, worldY=10, posX=158, posY=141, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=12, posX=105, posY=23, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=12, posX=148, posY=276, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=9, worldY=21, posX=64, posY=13, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=21, posX=275, posY=81, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=9, worldY=20, posX=11, posY=85, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=19, posX=188, posY=45, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=19, posX=14, posY=107, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=19, posX=21, posY=79, posZ=1, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=20, posX=231, posY=17, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=19, posX=164, posY=14, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=19, posX=160, posY=45, posZ=1, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=18, posX=63, posY=236, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=18, posX=82, posY=286, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=19, posX=95, posY=210, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=10, worldY=22, posX=80, posY=175, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=21, posX=217, posY=172, town="Brandenburg", type="Residential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=21, posX=56, posY=45, posZ=1, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=22, posX=19, posY=275, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=4, worldY=24, posX=269, posY=111, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=25, posX=264, posY=237, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=26, posX=126, posY=158, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=2, worldY=32, posX=162, posY=126, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=1, worldY=32, posX=136, posY=219, posZ=1, town="Ekron", type="Residential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=3, worldY=32, posX=39, posY=194, posZ=1, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=33, posX=102, posY=53, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=3, worldY=36, posX=287, posY=26, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=2, worldY=36, posX=157, posY=23, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=40, posX=125, posY=15, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=4, worldY=41, posX=269, posY=77, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=13, worldY=31, posX=213, posY=63, town="Doe Valley Forest", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=13, worldY=31, posX=202, posY=161, town="Doe Valley Forest", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=13, worldY=33, posX=188, posY=41, town="Doe Valley Forest", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=11, worldY=33, posX=150, posY=238, town="Doe Valley Forest", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=12, worldY=40, posX=228, posY=237, town="Echo Creek", type="Residential", cat="Cabin", hardcore=false, majorTown=true, balance=false, },
        { worldX=12, worldY=41, posX=219, posY=4, town="Echo Creek", type="Residential", cat="Cabin", hardcore=false, majorTown=true, balance=false, },
        { worldX=10, worldY=40, posX=113, posY=53, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=35, posX=196, posY=237, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=36, posX=251, posY=84, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=9, worldY=41, posX=236, posY=218, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=9, worldY=41, posX=128, posY=260, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=2, worldY=40, posX=264, posY=195, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=4, worldY=45, posX=124, posY=291, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=3, worldY=47, posX=79, posY=168, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=4, worldY=47, posX=112, posY=109, town="Irvington", type="Residential", cat="Cabin", hardcore=false, majorTown=true, balance=false, },
        { worldX=13, worldY=48, posX=233, posY=136, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=13, worldY=45, posX=19, posY=275, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=11, worldY=44, posX=249, posY=277, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=9, worldY=44, posX=218, posY=64, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=232, posY=203, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=9, worldY=46, posX=25, posY=22, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=172, posY=99, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=22, posY=58, posZ=1, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=25, posY=244, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=134, posY=260, posZ=1, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=122, posY=265, posZ=1, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=47, posX=185, posY=214, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=47, posX=154, posY=289, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=194, posY=31, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=217, posY=63, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=10, worldY=49, posX=3, posY=47, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=9, worldY=48, posX=199, posY=288, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=9, worldY=49, posX=151, posY=239, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=9, posY=58, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=47, posX=230, posY=64, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=47, posX=83, posY=213, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=48, posX=136, posY=75, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=48, posX=83, posY=74, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=48, posX=159, posY=180, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=49, posX=272, posY=24, posZ=2, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=49, posX=220, posY=10, town="Hog Wallow", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=25, worldY=47, posX=256, posY=207, town="Hog Wallow", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=27, worldY=46, posX=262, posY=204, town="Hog Wallow", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=27, worldY=48, posX=171, posY=188, town="Hog Wallow", type="Residential", cat="Cabin", hardcore=false, majorTown=false, balance=false, },
        { worldX=27, worldY=48, posX=231, posY=175, town="Hog Wallow", type="Residential", cat="Cabin", hardcore=false, majorTown=false, balance=false, },
        { worldX=27, worldY=48, posX=252, posY=181, town="Hog Wallow", type="Residential", cat="Cabin", hardcore=false, majorTown=false, balance=false, },
        { worldX=29, worldY=50, posX=129, posY=123, town="Hog Wallow", type="Residential", cat="Cabin", hardcore=false, majorTown=false, balance=false, },
        { worldX=28, worldY=48, posX=294, posY=91, town="Hog Wallow", type="Residential", cat="Cabin", hardcore=false, majorTown=false, balance=false, },
        { worldX=6, worldY=41, posX=82, posY=150, posZ=1, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=4, worldY=39, posX=21, posY=181, posZ=1, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=0, worldY=31, posX=47, posY=135, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=10, worldY=49, posX=276, posY=180, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=24, posX=64, posY=164, town="West Point", type="Residential", cat="Cabin", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=47, posX=112, posY=281, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=17, posX=295, posY=230, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=17, worldY=20, posX=295, posY=56, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=17, posX=79, posY=258, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=57, posY=249, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=266, posY=228, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=18, posX=282, posY=49, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=18, posX=284, posY=106, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=18, posX=219, posY=79, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=18, posX=227, posY=31, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=17, posX=115, posY=231, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=18, posX=159, posY=87, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=28, worldY=39, posX=48, posY=109, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=37, worldY=22, posX=197, posY=130, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=37, worldY=22, posX=267, posY=275, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=80, posY=124, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=22, posX=94, posY=102, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=133, posY=24, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=137, posY=86, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=22, posX=240, posY=277, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=22, posX=243, posY=96, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=59, posY=84, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=72, posY=152, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=92, posY=186, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=196, posY=115, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=204, posY=125, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=3, posY=173, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=54, posY=294, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=34, posX=63, posY=47, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=84, posY=259, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=117, posY=193, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=119, posY=231, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=31, posX=151, posY=190, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=32, worldY=42, posX=283, posY=212, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
    }
    return points
end
