function RSL_SpawnPoints_Residential_A()
    local points = {
        { worldX=46, worldY=17, posX=285, posY=37, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=16, posX=231, posY=289, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=44, worldY=16, posX=149, posY=171, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=43, worldY=17, posX=153, posY=90, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=43, worldY=16, posX=119, posY=287, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=16, posX=146, posY=184, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=41, worldY=19, posX=279, posY=191, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=19, posX=48, posY=20, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=18, posX=41, posY=120, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=17, posX=12, posY=152, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=41, worldY=17, posX=285, posY=82, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=41, worldY=16, posX=217, posY=259, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=39, worldY=23, posX=281, posY=18, posZ=1, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=249, posY=14, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=158, posY=23, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=172, posY=11, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=160, posY=288, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=169, posY=286, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=173, posY=85, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=172, posY=157, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=126, posY=189, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=79, posY=127, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=22, posX=171, posY=169, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=37, worldY=22, posX=148, posY=207, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=241, posY=27, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=109, posY=28, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=31, posY=25, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=166, posY=98, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=128, posY=128, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=92, posY=83, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=37, worldY=23, posX=268, posY=125, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=37, worldY=23, posX=210, posY=36, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=174, posY=19, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=165, posY=25, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=181, posY=32, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=171, posY=59, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=42, posX=252, posY=190, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=42, posX=280, posY=159, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=42, posX=122, posY=128, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=42, posX=61, posY=96, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=42, posX=61, posY=36, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=42, posX=80, posY=210, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=42, posX=21, posY=144, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=43, posX=130, posY=223, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=43, posX=104, posY=129, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=12, posY=214, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=72, posY=179, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=32, worldY=43, posX=223, posY=125, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=32, worldY=43, posX=251, posY=73, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=32, worldY=42, posX=252, posY=192, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=32, worldY=42, posX=251, posY=81, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=292, posY=113, posZ=1, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=285, posY=127, posZ=1, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=293, posY=208, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=18, posX=162, posY=63, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=17, posX=204, posY=269, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=18, posX=50, posY=112, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=18, posX=162, posY=182, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=18, posX=37, posY=111, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=17, posX=40, posY=174, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=17, posX=73, posY=148, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=20, posX=283, posY=92, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=20, posX=234, posY=63, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=20, posX=227, posY=6, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=19, posX=274, posY=269, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=19, posX=253, posY=243, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=22, posX=175, posY=129, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=22, posX=175, posY=44, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=29, posX=100, posY=53, town="Fallas Lake", type="Residential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=29, posX=165, posY=124, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=39, worldY=29, posX=137, posY=169, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=39, worldY=29, posX=120, posY=169, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=39, worldY=29, posX=96, posY=139, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=39, worldY=29, posX=67, posY=81, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=39, worldY=29, posX=56, posY=103, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=39, worldY=29, posX=30, posY=128, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=39, worldY=29, posX=15, posY=97, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=48, posY=186, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=79, posY=254, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=104, posY=203, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=144, posY=234, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=295, posY=81, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=35, worldY=31, posX=198, posY=54, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=156, posY=120, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=31, posX=58, posY=105, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=247, posY=157, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=31, posX=72, posY=191, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=31, posX=133, posY=219, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=165, posY=248, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=222, posY=281, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=145, posY=70, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=152, posY=69, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=186, posY=63, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=226, posY=35, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=283, posY=113, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=153, posY=115, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=92, posY=120, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=146, posY=81, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=150, posY=107, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=176, posY=133, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=197, posY=177, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=279, posY=208, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=39, posY=196, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=87, posY=246, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=52, posY=247, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=190, posY=273, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=254, posY=14, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=279, posY=278, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=56, posY=279, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=84, posY=20, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=85, posY=56, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=109, posY=95, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=6, posY=117, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=237, posY=91, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=73, posY=218, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=40, posY=284, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=34, posX=19, posY=205, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=251, posY=220, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=29, posX=57, posY=104, town="Dixie", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=false, },
        { worldX=19, worldY=17, posX=111, posY=217, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=249, posY=156, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=22, posX=222, posY=281, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=111, posY=120, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=176, posY=221, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=137, posY=175, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=108, posY=135, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=174, posY=78, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=12, posX=270, posY=65, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=12, posX=28, posY=20, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=11, posX=59, posY=248, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=11, posX=274, posY=174, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=12, posX=284, posY=214, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=12, posX=238, posY=81, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=165, posY=71, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=148, posY=48, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=11, posX=46, posY=41, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=10, posX=281, posY=203, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=13, posY=139, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=10, posX=84, posY=63, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=104, posY=280, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=9, posX=190, posY=188, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=9, posX=167, posY=191, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=9, posX=197, posY=186, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=9, posX=179, posY=209, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=9, posX=119, posY=205, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=9, posX=130, posY=233, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=9, posX=116, posY=220, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=9, posX=276, posY=257, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=9, posX=274, posY=191, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=55, posY=188, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=120, posY=233, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=8, posX=20, posY=199, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=7, posX=25, posY=166, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=219, posY=271, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=286, posY=92, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=6, posX=266, posY=290, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=7, posX=215, posY=135, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=7, posX=141, posY=217, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=8, posX=132, posY=22, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=8, posX=193, posY=94, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=175, posY=266, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=131, posY=216, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=238, posY=69, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=219, posY=33, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=115, posY=15, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=61, posY=15, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=52, posY=37, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=23, posY=19, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=12, posY=80, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=37, posY=75, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=75, posY=135, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=73, posY=128, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=44, posY=122, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=48, posY=194, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=65, posY=172, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=80, posY=178, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=68, posY=203, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=77, posY=225, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=68, posY=217, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=31, posY=273, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=12, posY=268, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=13, posY=242, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=18, posY=177, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=264, posY=284, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=287, posY=270, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=31, posY=267, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=55, posY=270, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=49, posY=289, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=41, posY=10, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=47, posY=42, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=18, posY=69, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=270, posY=39, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=27, posY=141, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=51, posY=129, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=82, posY=62, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=72, posY=29, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=81, posY=22, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=80, posY=287, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=73, posY=264, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=277, posY=75, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=290, posY=87, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=292, posY=71, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=266, posY=88, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=4, posX=276, posY=66, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=17, posY=131, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=3, posY=133, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=34, posY=190, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=13, posY=206, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=49, posY=205, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=77, posY=193, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=74, posY=163, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=35, posY=164, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=42, posY=178, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=47, posY=165, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=27, posY=178, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=132, posY=192, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=123, posY=188, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=121, posY=186, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=193, posY=196, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=188, posY=182, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=174, posY=233, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=187, posY=217, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=140, posY=281, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=4, posX=160, posY=280, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=55, posY=81, posZ=14, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=16, posY=277, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=43, posY=235, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=40, posY=206, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=17, posY=217, posZ=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=15, posY=69, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=15, posY=90, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=16, posY=105, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=24, posY=130, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=17, posY=137, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=13, posY=130, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=22, posY=130, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=25, posY=137, posZ=4, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=14, posY=130, posZ=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=6, posX=227, posY=269, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=224, posY=22, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=256, posY=36, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=282, posY=82, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=270, posY=71, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=228, posY=101, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=7, posX=234, posY=140, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=8, posX=292, posY=217, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=11, posY=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=276, posY=39, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=41, worldY=9, posX=279, posY=101, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=10, posX=121, posY=20, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=10, posX=203, posY=137, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=10, posX=171, posY=223, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=11, posX=18, posY=5, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=16, posY=166, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=16, posY=65, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=10, posX=255, posY=112, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=187, posY=257, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=225, posY=235, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=259, posY=203, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=235, posY=182, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=140, posY=137, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=89, posY=88, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=126, posY=46, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=162, posY=72, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=187, posY=78, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=227, posY=71, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=258, posY=68, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=295, posY=41, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=9, posX=255, posY=112, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=9, posX=16, posY=46, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=280, posY=87, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=208, posY=13, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=9, posX=95, posY=283, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=149, posY=49, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=156, posY=85, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=209, posY=156, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=221, posY=242, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=11, posX=159, posY=82, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=11, posX=108, posY=81, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=11, posX=61, posY=105, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=11, posX=15, posY=40, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=72, posY=78, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=9, posX=223, posY=276, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=52, posY=27, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=130, posY=249, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=131, posY=273, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=209, posY=84, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=193, posY=119, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=167, posY=178, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=254, posY=293, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=11, posX=125, posY=58, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=11, posX=94, posY=10, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=11, posX=47, posY=34, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=11, posX=28, posY=91, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=11, posX=194, posY=92, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=153, posY=278, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=107, posY=230, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=62, posY=266, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=11, posX=12, posY=14, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=202, posY=132, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=133, posY=140, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=102, posY=169, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=34, posY=137, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=13, posY=181, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=11, posX=73, posY=17, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=11, posX=135, posY=15, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=160, posY=191, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=69, posY=8, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=9, posX=113, posY=285, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=9, posX=110, posY=230, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=9, posX=73, posY=174, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=9, posX=138, posY=38, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=8, posX=284, posY=91, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=8, posX=200, posY=72, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=8, posX=225, posY=15, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=8, posX=65, posY=112, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=8, posX=281, posY=92, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=8, posX=237, posY=94, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=8, posX=235, posY=176, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=9, posX=64, posY=102, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=9, posX=277, posY=208, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=8, posX=263, posY=248, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=8, posX=170, posY=221, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=8, posX=81, posY=244, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=8, posX=11, posY=265, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=214, posY=163, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=8, posX=264, posY=41, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=9, posX=48, posY=182, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=9, posX=153, posY=185, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=9, posX=46, posY=252, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=9, posX=111, posY=230, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=47, worldY=9, posX=38, posY=183, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=47, worldY=9, posX=19, posY=270, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=47, worldY=9, posX=115, posY=238, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=47, worldY=9, posX=157, posY=224, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=47, worldY=9, posX=151, posY=65, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=47, worldY=9, posX=190, posY=20, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=47, worldY=9, posX=47, posY=21, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=8, posX=283, posY=236, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=7, posX=266, posY=280, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=47, worldY=7, posX=84, posY=239, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=7, posX=248, posY=141, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=7, posX=107, posY=167, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=false, },
    }
    return points
end
