function RSL_SpawnPoints_NonRes_Other_A()
    local points = {
        { worldX=45, worldY=19, posX=137, posY=187, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=124, posY=195, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=123, posY=164, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=137, posY=171, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=76, posY=191, posZ=1, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=19, posX=136, posY=65, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=19, posX=182, posY=113, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=19, posX=185, posY=172, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=19, posX=124, posY=167, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=19, posX=87, posY=184, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=19, posX=82, posY=81, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=19, posX=82, posY=61, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=18, posX=237, posY=242, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=18, posX=185, posY=273, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=18, posX=167, posY=273, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=18, posX=167, posY=273, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=18, posX=151, posY=267, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=18, posX=116, posY=274, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=18, posX=105, posY=271, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=18, posX=87, posY=271, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=158, posY=70, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=155, posY=83, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=155, posY=75, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=103, posY=60, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=108, posY=54, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=73, posY=60, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=81, posY=50, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=19, posX=158, posY=43, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=18, posX=286, posY=53, town="Valley Station", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=16, posX=165, posY=67, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=16, posX=135, posY=65, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=43, worldY=18, posX=197, posY=49, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=43, worldY=17, posX=203, posY=209, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=43, worldY=17, posX=110, posY=224, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=43, worldY=17, posX=108, posY=213, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=43, worldY=17, posX=157, posY=196, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=43, worldY=17, posX=159, posY=201, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=16, posX=253, posY=51, town="Valley Station", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=16, posX=272, posY=67, town="Valley Station", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=16, posX=268, posY=48, town="Valley Station", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=15, posX=28, posY=232, town="Valley Station", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=15, posX=25, posY=208, town="Valley Station", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=19, posX=144, posY=12, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=19, posX=148, posY=19, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=19, posX=135, posY=75, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=21, posX=243, posY=104, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=21, posX=231, posY=131, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=41, worldY=19, posX=270, posY=23, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=41, worldY=17, posX=268, posY=273, town="Valley Station", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=false, },
        { worldX=42, worldY=17, posX=27, posY=225, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=41, worldY=17, posX=248, posY=168, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=41, worldY=17, posX=246, posY=165, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=41, worldY=17, posX=242, posY=115, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=40, worldY=23, posX=41, posY=23, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=23, posX=19, posY=17, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=23, posX=13, posY=19, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=23, posX=17, posY=35, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=287, posY=46, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=271, posY=37, posZ=2, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=284, posY=13, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=274, posY=13, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=260, posY=11, town="West Point", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=232, posY=28, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=242, posY=17, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=232, posY=40, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=200, posY=48, town="West Point", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=210, posY=15, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=203, posY=17, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=166, posY=11, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=171, posY=12, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=159, posY=12, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=23, posX=160, posY=26, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=22, posX=30, posY=266, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=22, posX=19, posY=251, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=271, posY=287, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=263, posY=279, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=267, posY=277, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=275, posY=285, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=250, posY=287, town="West Point", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=250, posY=287, town="West Point", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=206, posY=286, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=196, posY=279, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=194, posY=288, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=184, posY=289, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=187, posY=283, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=169, posY=286, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=160, posY=288, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=161, posY=273, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=124, posY=270, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=273, posY=213, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=282, posY=207, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=22, posX=73, posY=160, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=234, posY=200, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=239, posY=198, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=233, posY=187, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=39, worldY=22, posX=199, posY=213, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=23, posX=149, posY=180, town="West Point", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=23, posX=141, posY=204, town="West Point", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=23, posX=80, posY=175, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=23, posX=78, posY=180, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=280, posY=139, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=271, posY=136, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=259, posY=136, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=264, posY=168, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=23, posX=256, posY=185, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=37, worldY=22, posX=227, posY=194, town="West Point", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=37, worldY=22, posX=283, posY=174, town="West Point", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=22, posX=291, posY=116, town="West Point", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=24, posX=48, posY=167, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=24, posX=65, posY=165, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=30, posX=287, posY=241, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=33, posX=177, posY=192, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=31, posX=175, posY=249, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=32, posX=133, posY=47, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=32, posX=152, posY=30, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=31, posX=142, posY=120, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=31, posX=106, posY=113, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=31, posX=106, posY=100, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=31, posX=120, posY=36, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=31, posX=132, posY=17, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=30, posX=148, posY=256, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=30, posX=116, posY=256, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=113, posY=9, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=112, posY=17, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=128, posY=77, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=103, posY=107, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=108, posY=111, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=115, posY=138, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=126, posY=142, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=120, posY=138, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=109, posY=164, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=110, posY=169, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=107, posY=176, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=129, posY=214, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=31, posX=127, posY=207, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=121, posY=12, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=121, posY=8, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=126, posY=98, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=125, posY=95, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=117, posY=203, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=132, posY=201, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=132, posY=201, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=131, posY=230, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=120, posY=233, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=114, posY=287, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=112, posY=6, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=122, posY=4, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=133, posY=6, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=148, posY=4, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=151, posY=25, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=152, posY=22, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=122, posY=74, town="Muldraugh", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=114, posY=81, town="Muldraugh", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=113, posY=69, town="Muldraugh", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=122, posY=138, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=106, posY=211, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=127, posY=232, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=131, posY=237, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=127, posY=247, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=126, posY=253, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=118, posY=255, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=114, posY=59, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=110, posY=102, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=115, posY=104, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=110, posY=117, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=108, posY=133, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=109, posY=144, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=109, posY=150, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=109, posY=158, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=114, posY=166, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=112, posY=175, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=136, posY=214, town="Muldraugh", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=35, posX=124, posY=28, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=35, posX=125, posY=34, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=35, posX=122, posY=61, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=35, posX=262, posY=54, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=35, posX=268, posY=45, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=35, posX=268, posY=53, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=153, posY=53, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=225, posY=113, town="Muldraugh", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=31, posX=41, posY=230, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=51, posY=162, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=119, posY=155, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=107, posY=159, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=107, posY=159, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=32, posX=117, posY=242, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=200, posY=224, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=82, posY=135, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=33, posX=77, posY=129, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=190, posY=106, town="Muldraugh", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=198, posY=212, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=196, posY=203, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=33, posX=247, posY=259, town="Muldraugh", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=182, posY=139, posZ=4, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=183, posY=116, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=190, posY=159, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=201, posY=248, posZ=3, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=217, posY=228, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=37, posX=212, posY=46, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=37, posX=208, posY=52, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=36, posX=37, posY=221, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=36, posX=13, posY=214, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=282, posY=152, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=285, posY=141, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=178, posY=232, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=186, posY=243, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=93, posY=176, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=103, posY=171, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=79, posY=147, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=116, posY=129, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=167, posY=89, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=178, posY=100, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=189, posY=73, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=231, posY=82, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=131, posY=45, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=36, posX=138, posY=19, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=283, posY=208, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=288, posY=194, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=282, posY=182, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=276, posY=80, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=278, posY=46, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=282, posY=50, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=242, posY=186, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=223, posY=193, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=255, posY=150, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=247, posY=153, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=242, posY=150, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=230, posY=154, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=211, posY=154, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=176, posY=204, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=171, posY=204, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=129, posY=142, town="March Ridge", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=153, posY=143, town="March Ridge", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=128, posY=128, town="March Ridge", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=125, posY=149, town="March Ridge", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=104, posY=66, town="March Ridge", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=95, posY=46, town="March Ridge", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=42, posX=106, posY=54, town="March Ridge", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=37, posX=278, posY=211, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=37, posX=270, posY=211, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=37, posX=273, posY=244, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=277, posY=30, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=287, posY=7, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=279, posY=6, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=275, posY=55, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=222, posY=32, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=290, posY=93, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=287, posY=103, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=283, posY=113, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=287, posY=110, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=291, posY=129, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=287, posY=130, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=293, posY=138, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=292, posY=155, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=290, posY=116, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=289, posY=193, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=282, posY=195, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=288, posY=223, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=282, posY=220, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=38, posX=255, posY=270, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=39, posX=274, posY=41, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=39, posX=258, posY=51, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=37, posX=55, posY=225, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=38, posX=36, posY=84, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=38, posX=45, posY=71, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=38, posX=24, posY=158, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=39, posX=48, posY=40, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=38, posX=237, posY=197, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=38, posX=229, posY=198, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=38, posX=258, posY=214, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=39, posX=141, posY=130, town="Rosewood", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=39, posX=138, posY=116, town="Rosewood", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=40, posX=185, posY=221, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=40, posX=144, posY=232, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=39, posX=21, posY=187, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=253, posY=270, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=93, posY=268, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=94, posY=81, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=248, posY=67, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=251, posY=195, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=238, posY=202, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=206, posY=189, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=175, posY=165, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=167, posY=164, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=140, posY=153, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=147, posY=153, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=187, posY=183, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=195, posY=197, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=27, posX=39, posY=102, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=27, posX=92, posY=191, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=27, posX=55, posY=175, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=27, posX=56, posY=188, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=27, posX=56, posY=193, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=27, posX=49, posY=195, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=27, posX=54, posY=283, town="Fallas Lake", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=27, posX=96, posY=292, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=261, posY=118, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=254, posY=111, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=281, posY=126, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=293, posY=127, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=263, posY=275, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=213, posY=252, posZ=5, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=195, posY=241, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=213, posY=204, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=206, posY=205, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=135, posY=166, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=159, posY=196, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=154, posY=204, posZ=6, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=139, posY=200, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=131, posY=197, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=103, posY=215, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=109, posY=238, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=67, posY=229, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=62, posY=221, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
    }
    return points
end
