function RSL_SpawnPoints_Balanced()
    return {
        -- Brandenburg
        { worldX= 9, worldY=21, posX=  4, posY= 35, town="Brandenburg", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Bright Valley Trailer Park 2 ID:2409,
        { worldX= 8, worldY=21, posX= 83, posY=203, town="Brandenburg", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg Nice House 1 Brandenburg Bypass ID:2414,
        { worldX= 7, worldY=19, posX=110, posY=166, town="Brandenburg", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg Nice House 2 E Lawrence Ln ID:2415,
        { worldX= 7, worldY=20, posX= 38, posY=265, posZ=1, town="Brandenburg", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg Nice House 3 cross St ID:2416,
        { worldX= 7, worldY=19, posX= 21, posY= 79, posZ=1, town="Brandenburg", type="Residential", cat="Home", cat2="Apartment", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg Apartment 1 Above Buck Naked ID:2421,
        { worldX= 6, worldY=19, posX=239, posY=120, posZ=1, town="Brandenburg", type="Residential", cat="Home", cat2="Apartment", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg Apartment 2 Above Chophouse ID:2423,
        { worldX= 6, worldY=20, posX= 19, posY=104, town="Brandenburg", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg House 1 Howard Drive ID:2440,
        { worldX= 5, worldY=19, posX=271, posY= 48, town="Brandenburg", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg House 3 Lawrence St ID:2443,
        { worldX= 5, worldY=20, posX=139, posY=104, town="Brandenburg", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg House 6 Hammer St ID:2452,
        { worldX= 8, worldY=20, posX= 77, posY=154, town="Brandenburg", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg House 7 Woodrow St ID:2453,
        { worldX= 7, worldY=21, posX= 42, posY= 50, town="Brandenburg", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg Townhouse 1 Ohio Dr ID:2470,
        { worldX= 5, worldY=21, posX= 38, posY=105, town="Brandenburg", type="Residential", cat="Home", cat2="Rural", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Brandenburg Rural House 1 Windsor Drive ID:2481,
        -- Echo Creek
        { worldX=13, worldY=35, posX= 98, posY=254, town="Echo Creek", type="Residential", cat="Home", cat2="Rural", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek Egg Farm House ID:2541,
        { worldX=13, worldY=37, posX=273, posY= 29, town="Echo Creek", type="Residential", cat="Home", cat2="Rural", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek Rural House 3 Frog Jump Road ID:2542,
        { worldX=13, worldY=38, posX=274, posY=169, town="Echo Creek", type="Residential", cat="Home", cat2="Rural", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek Rural House 4 Frog Jump Road ID:2543,
        { worldX=12, worldY=38, posX=281, posY=187, town="Echo Creek", type="Residential", cat="Home", cat2="Rural", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek Rural House 5 Johannes Road ID:2544,
        { worldX=12, worldY=36, posX=149, posY=194, town="Echo Creek", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek House 1 Wilde Road ID:2545,
        { worldX=11, worldY=36, posX=266, posY=103, posZ=1, town="Echo Creek", type="Residential", cat="Home", cat2="Apartment", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek Diner Garage Apartment ID:2547,
        { worldX=11, worldY=36, posX=126, posY=105, town="Echo Creek", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek Trailer 1 Creek Lane ID:2550,
        { worldX=11, worldY=36, posX=211, posY= 83, town="Echo Creek", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek Trailer 2 Creek Lane ID:2551,
        { worldX=11, worldY=36, posX=243, posY=206, town="Echo Creek", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek House 2 Forest ave ID:2552,
        { worldX=11, worldY=36, posX=161, posY=248, town="Echo Creek", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek House 3 Forest Ave ID:2553,
        { worldX=11, worldY=37, posX=279, posY= 69, town="Echo Creek", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Echo Creek House 4 Winter Dr ID:2554,
        { worldX=11, worldY=36, posX=95, posY=207, town="Echo Creek", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Creek Lane,
        -- Ekron
        { worldX= 1, worldY=31, posX=189, posY= 15, town="Ekron", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron House 1 Old Ekron Road ID:2495,
        { worldX= 1, worldY=31, posX=140, posY=100, town="Ekron", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron House 2 Old Ekron Road ID:2496,
        { worldX= 1, worldY=32, posX= 98, posY= 50, town="Ekron", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron House 3 West Alley St ID:2497,
        { worldX= 2, worldY=32, posX= 64, posY= 60, town="Ekron", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron House 4 Broad Willie Dr ID:2498,
        { worldX=2, worldY=32, posX=200, posY=38, posZ=1, town="Ekron", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron House 5 Larry Dr ID:2499,
        { worldX= 3, worldY=32, posX= 15, posY= 18, town="Ekron", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron Trailer 1 Wagon Rest St ID:2500,
        { worldX= 3, worldY=31, posX= 55, posY=294, town="Ekron", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron Trailer 2 Wagon Rest St ID:2501,
        { worldX= 2, worldY=32, posX=162, posY=126, town="Ekron", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron House 6 Berry Dr ID:2502,
        { worldX= 1, worldY=32, posX=280, posY=280, town="Ekron", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron House 7 Railway St ID:2503,
        { worldX= 3, worldY=33, posX= 33, posY= 57, town="Ekron", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron House 8 Stringtown Road ID:2504,
        { worldX= 1, worldY=32, posX=123, posY=262, posZ=1, town="Ekron", type="Residential", cat="Home", cat2="Apartment", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Ekron Apartment Above Gun Store ID:2516,
        { worldX=2, worldY=32, posX=253, posY=119, posZ=1, town="Ekron", type="Residential", cat="Home", cat2="Apartment", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Berry Drive N/A
        -- Fallas Lake
        { worldX=24, worldY=27, posX=100, posY= 96, town="Fallas Lake", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- apartment above gas station ID:479,
        { worldX=24, worldY=27, posX=211, posY=153, town="Fallas Lake", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- medium house by lake ID:500,
        { worldX=24, worldY=27, posX=12, posY=106, town="Fallas Lake", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- medium house 1 ID:501,
        { worldX=23, worldY=28, posX=294, posY= 20, town="Fallas Lake", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- medium house 2 ID:502,
        { worldX=24, worldY=27, posX=9, posY=151, town="Fallas Lake", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house house 1 ID:503,
        { worldX=23, worldY=27, posX=231, posY=170, town="Fallas Lake", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house house 2 ID:504,
        { worldX=23, worldY=27, posX=224, posY=254, town="Fallas Lake", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house house 3 ID:505,
        { worldX=23, worldY=27, posX=189, posY=271, town="Fallas Lake", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 1 ID:506,
        { worldX=23, worldY=27, posX=289, posY=242, town="Fallas Lake", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 2 ID:507,
        { worldX=26, worldY=29, posX=100, posY= 53, town="Fallas Lake", type="NonResidential", cat="Farm", cat2="Rural", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- eastern Fallas farm 7, by triple warehouses ID:736,
        { worldX=24, worldY=28, posX=290, posY=106, town="Fallas Lake", type="NonResidential", cat="Farm", cat2="Rural", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- eastern Fallas farm 8, close to town ID:737,
        { worldX=24, worldY=27, posX=13, posY=188, town="Fallas Lake", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Greer Street,
        -- Irvington
        { worldX= 8, worldY=45, posX=139, posY=233, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvignton House 1 Cattle Road ID:2585,
        { worldX= 9, worldY=46, posX= 90, posY= 97, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvington House 2 Beaver St ID:2586,
        { worldX= 8, worldY=46, posX= 40, posY= 61, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvington House 5 Lincoln St ID:2590,
        { worldX= 6, worldY=44, posX= 13, posY=237, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvington House 6 by Scrapyard ID:2592,
        { worldX= 7, worldY=46, posX=224, posY=177, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvington House 7 Pearl Ln ID:2598,
        { worldX= 8, worldY=46, posX=113, posY=255, posZ=1, town="Irvington", type="Residential", cat="Home", cat2="Apartment", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Apartment Above Antique store ID:2606,
        { worldX= 8, worldY=47, posX=219, posY= 76, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvington House 9 Church st ID:2612,
        { worldX= 8, worldY=47, posX=186, posY=267, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvington Trailer 1 Woodlawn Dr ID:2614,
        { worldX= 8, worldY=48, posX=251, posY= 63, posZ=1, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvington Townhouse 2 KY79 ID:2619,
        { worldX=10, worldY=48, posX=125, posY=169, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvington house 11 Donkey road ID:2620,
        { worldX= 6, worldY=47, posX=255, posY=275, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvington Trailer 5 High st ID:2650,
        { worldX= 5, worldY=48, posX=278, posY=249, posZ=2, town="Irvington", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Irvington Townhouse 4 West st ID:2661,
        -- Louisville
        { worldX=41, worldY=11, posX= 15, posY= 61, town="Louisville", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- South LV Suburb 2, Big House 4 ID:1021,
        { worldX=40, worldY= 8, posX= 21, posY=262, town="Louisville", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- LV River house, Big 1 ID:1061,
        { worldX=40, worldY= 6, posX=232, posY=150, town="Louisville", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- West LV Suburb 1,Medium house 2 ID:1076,
        { worldX=40, worldY= 4, posX=200, posY=284, town="Louisville", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- north west LV toownhouse 1 ID:1204,
        { worldX=42, worldY=11, posX=276, posY= 29, town="Louisville", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- South Louisville Suburb 4, small house 4 ID:1575,
        { worldX=42, worldY= 9, posX=256, posY= 29, town="Louisville", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- Schnitzelburg Townhouse 11 ID:1593,
        { worldX=46, worldY=10, posX=127, posY=237, town="Louisville", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- South East Louisville suburb 3, big house 3 ID:1695,
        { worldX=46, worldY= 8, posX=290, posY=155, town="Louisville", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- East LV Suburb 2, big house 2 ID:1758,
        { worldX=43, worldY= 6, posX= 18, posY=121, posZ=3, town="Louisville", type="Residential", cat="Home", cat2="Apartment", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- phoenix hill apartment block 2, nice apartment 3 ID:1945,
        { worldX=45, worldY= 6, posX= 59, posY= 28, town="Louisville", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- butchertown, small house 5 ID:2023,
        { worldX=42, worldY= 4, posX=266, posY=246, posZ=2, town="Louisville", type="Residential", cat="Home", cat2="Apartment", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- c louisville high street apartments, apartment 4 ID:2125,
        { worldX=43, worldY= 4, posX=280, posY= 64, posZ=1, town="Louisville", type="Residential", cat="Home", cat2="Apartment", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- apartment above laundry ID:2219,
        -- March Ridge
        { worldX=33, worldY=42, posX=207, posY= 28, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- dormitory quad 1 ID:365,
        { worldX=33, worldY=42, posX=194, posY= 17, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- dormitory quad 2 ID:366,
        { worldX=33, worldY=42, posX=158, posY= 42, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- dormitory quad 4 ID:368,
        { worldX=34, worldY=42, posX=246, posY=226, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- townhouse 1 ID:370,
        { worldX=34, worldY=42, posX=266, posY=125, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 1 ID:373,
        { worldX=34, worldY=42, posX=185, posY= 51, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 2 ID:374,
        { worldX=34, worldY=42, posX= 92, posY= 68, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 5 ID:377,
        { worldX=34, worldY=42, posX= 16, posY=200, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- townhouse 4 ID:380,
        { worldX=33, worldY=43, posX= 24, posY= 53, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 3 ID:384,
        { worldX=33, worldY=42, posX=  8, posY= 77, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 6 ID:387,
        { worldX=32, worldY=43, posX=245, posY=204, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- townhouse 1 ID:388,
        { worldX=32, worldY=42, posX=253, posY=245, town="March Ridge", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- townhouse 4 ID:391,
        -- Muldraugh
        { worldX=35, worldY=31, posX=151, posY= 73, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 1 ID:838,
        { worldX=35, worldY=31, posX=289, posY=118, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 2 ID:841,
        { worldX=36, worldY=31, posX=144, posY= 72, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 3 ID:844,
        { worldX=35, worldY=32, posX=195, posY=  9, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- medium house 3 ID:849,
        { worldX=36, worldY=32, posX=108, posY=42, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- trailer 4 ID:857,
        { worldX=36, worldY=32, posX=176, posY=189, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- trailer 8 ID:861,
        { worldX=35, worldY=32, posX=233, posY=161, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 2 ID:863,
        { worldX=35, worldY=32, posX=195, posY=293, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 4 ID:869,
        { worldX=36, worldY=33, posX=110, posY=134, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- medium house 5 ID:876,
        { worldX=35, worldY=33, posX=221, posY=275, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 9 ID:881,
        { worldX=36, worldY=34, posX= 53, posY= 84, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- medium house 7 ID:882,
        { worldX=35, worldY=34, posX=279, posY=234, town="Muldraugh", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- trailer 2 ID:884,
        -- Riverside
        { worldX=22, worldY=17, posX=164, posY=222, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 3 ID:576,
        { worldX=22, worldY=18, posX= 68, posY= 73, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 4 ID:577,
        { worldX=22, worldY=18, posX=205, posY= 32, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 1 ID:584,
        { worldX=21, worldY=18, posX=201, posY=182, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 2 ID:585,
        { worldX=21, worldY=18, posX= 90, posY=182, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 4 ID:587,
        { worldX=21, worldY=18, posX= 27, posY= 20, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 5 ID:588,
        { worldX=20, worldY=18, posX=115, posY= 62, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 1 ID:590,
        { worldX=20, worldY=17, posX= 76, posY=247, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 2, nice ID:591,
        { worldX=19, worldY=17, posX= 91, posY=216, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 3 ID:592,
        { worldX=17, worldY=20, posX=274, posY=106, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- trailer 1 ID:607,
        { worldX=17, worldY=20, posX=270, posY= 25, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- trailer 4 ID:610,
        { worldX=17, worldY=19, posX=221, posY=261, town="Riverside", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- trailer 8 ID:614,
        -- Rosewood
        { worldX=26, worldY=38, posX=285, posY= 88, posZ=1, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small apartment over clothes store ID:410,
        { worldX=26, worldY=38, posX=290, posY=150, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- apartment over dr salon ID:419,
        { worldX=26, worldY=38, posX=282, posY=217, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small apartment over fudge store ID:426,
        { worldX=26, worldY=38, posX=202, posY=144, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 1 ID:445,
        { worldX=26, worldY=38, posX=247, posY=124, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 2 ID:446,
        { worldX=27, worldY=38, posX=112, posY=156, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 1 ID:447,
        { worldX=27, worldY=38, posX=149, posY=205, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 1 ID:448,
        { worldX=27, worldY=38, posX=185, posY=155, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 2 ID:449,
        { worldX=28, worldY=38, posX= 20, posY=180, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- medium house 1 ID:450,
        { worldX=28, worldY=39, posX= 51, posY= 33, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 2 ID:451,
        { worldX=27, worldY=39, posX=226, posY=115, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 3 ID:452,
        { worldX=27, worldY=38, posX=116, posY=276, town="Rosewood", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 3 ID:453,
        -- West Point
        { worldX=39, worldY=23, posX=273, posY= 13, posZ=1, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- apartment 2, above hardware ID:103,
        { worldX=39, worldY=23, posX=130, posY= 12, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- apartment 4, above variety store ID:120,
        { worldX=39, worldY=22, posX=202, posY=156, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 1 ID:161,
        { worldX=39, worldY=22, posX=111, posY= 90, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 3 ID:165,
        { worldX=38, worldY=22, posX=259, posY=191, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 2 ID:167,
        { worldX=38, worldY=22, posX= 83, posY=247, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 4 ID:169,
        { worldX=38, worldY=22, posX= 15, posY=125, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 4 ID:170,
        { worldX=37, worldY=22, posX=188, posY= 70, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 5, near dock ID:175,
        { worldX=37, worldY=22, posX=178, posY=261, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 6 ID:176,
        { worldX=37, worldY=22, posX= 18, posY=122, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 8,nice ID:178,
        { worldX=38, worldY=23, posX=222, posY=122, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- small house 1 ID:183,
        { worldX=38, worldY=23, posX= 41, posY=105, town="West Point", type="Residential", cat="Home", cat2="Home", hardcore=false, majorTown=true, balance=true, wilderness=false }, -- big house 4, nice ID:187,
    }
end
