function RSL_SpawnPoints_Balanced_Residential()
    local points = {
        { worldX=46, worldY=17, posX=270, posY=102, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=44, worldY=16, posX=113, posY=208, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=44, worldY=16, posX=113, posY=136, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=43, worldY=17, posX=155, posY=138, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=43, worldY=17, posX=159, posY=34, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=42, worldY=16, posX=144, posY=208, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=42, worldY=20, posX=6, posY=5, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=42, worldY=19, posX=30, posY=32, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=41, worldY=18, posX=273, posY=222, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=42, worldY=17, posX=40, posY=276, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=41, worldY=17, posX=291, posY=182, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=41, worldY=17, posX=222, posY=41, town="Valley Station", type="Residential", cat="Home", hardcore=false, majorTown=false, balance=true, },
        { worldX=39, worldY=23, posX=273, posY=13, posZ=1, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=39, worldY=23, posX=130, posY=12, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=39, worldY=22, posX=202, posY=156, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=39, worldY=22, posX=111, posY=90, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=38, worldY=22, posX=259, posY=191, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=38, worldY=22, posX=83, posY=247, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=38, worldY=22, posX=15, posY=125, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=37, worldY=22, posX=188, posY=70, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=37, worldY=22, posX=178, posY=261, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=37, worldY=22, posX=18, posY=122, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=38, worldY=23, posX=222, posY=122, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=38, worldY=23, posX=41, posY=105, town="West Point", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=207, posY=28, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=194, posY=17, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=158, posY=42, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=34, worldY=42, posX=246, posY=226, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=34, worldY=42, posX=266, posY=125, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=34, worldY=42, posX=185, posY=51, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=34, worldY=42, posX=92, posY=68, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=34, worldY=42, posX=16, posY=200, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=43, posX=24, posY=53, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=8, posY=77, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=32, worldY=43, posX=245, posY=204, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=32, worldY=42, posX=253, posY=245, town="March Ridge", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=285, posY=88, posZ=1, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=290, posY=150, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=282, posY=217, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=202, posY=144, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=247, posY=124, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=27, worldY=38, posX=112, posY=156, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=27, worldY=38, posX=149, posY=205, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=27, worldY=38, posX=185, posY=155, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=28, worldY=38, posX=20, posY=180, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=28, worldY=39, posX=51, posY=33, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=27, worldY=39, posX=226, posY=115, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=27, worldY=38, posX=116, posY=276, town="Rosewood", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=100, posY=96, town="Fallas Lake", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=211, posY=153, town="Fallas Lake", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=12, posY=106, town="Fallas Lake", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=23, worldY=28, posX=294, posY=20, town="Fallas Lake", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=9, posY=151, town="Fallas Lake", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=23, worldY=27, posX=231, posY=170, town="Fallas Lake", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=23, worldY=27, posX=224, posY=254, town="Fallas Lake", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=23, worldY=27, posX=189, posY=271, town="Fallas Lake", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=23, worldY=27, posX=289, posY=242, town="Fallas Lake", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=22, worldY=17, posX=164, posY=222, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=22, worldY=18, posX=68, posY=73, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=22, worldY=18, posX=205, posY=32, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=21, worldY=18, posX=201, posY=182, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=21, worldY=18, posX=90, posY=182, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=21, worldY=18, posX=27, posY=20, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=20, worldY=18, posX=115, posY=62, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=20, worldY=17, posX=76, posY=247, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=19, worldY=17, posX=91, posY=216, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=17, worldY=20, posX=274, posY=106, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=17, worldY=20, posX=270, posY=25, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=17, worldY=19, posX=221, posY=261, town="Riverside", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=22, worldY=25, posX=218, posY=221, town="Fallas Lake", type="Residential", cat="Farm", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=28, posX=290, posY=106, town="Fallas Lake", type="Residential", cat="Farm", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=31, posX=151, posY=73, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=31, posX=289, posY=118, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=36, worldY=31, posX=144, posY=72, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=32, posX=195, posY=9, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=36, worldY=32, posX=108, posY=42, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=32, posX=233, posY=161, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=32, posX=195, posY=293, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=36, worldY=33, posX=110, posY=134, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=33, posX=221, posY=275, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=36, worldY=34, posX=53, posY=84, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=34, posX=279, posY=234, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=41, worldY=11, posX=15, posY=61, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=40, worldY=8, posX=21, posY=262, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=40, worldY=6, posX=232, posY=150, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=40, worldY=4, posX=200, posY=284, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=42, worldY=11, posX=276, posY=29, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=42, worldY=9, posX=256, posY=29, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=46, worldY=10, posX=127, posY=237, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=46, worldY=8, posX=290, posY=155, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=43, worldY=6, posX=18, posY=121, posZ=3, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=45, worldY=6, posX=59, posY=28, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=42, worldY=4, posX=266, posY=246, posZ=2, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=43, worldY=4, posX=280, posY=64, posZ=1, town="Louisville", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=9, worldY=21, posX=4, posY=35, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=21, posX=83, posY=203, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=7, worldY=19, posX=110, posY=166, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=7, worldY=20, posX=38, posY=265, posZ=1, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=19, posX=239, posY=120, posZ=1, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=20, posX=19, posY=104, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=5, worldY=19, posX=271, posY=48, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=5, worldY=20, posX=139, posY=104, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=20, posX=77, posY=154, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=7, worldY=21, posX=42, posY=50, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=5, worldY=21, posX=38, posY=105, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=31, posX=189, posY=15, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=31, posX=140, posY=100, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=32, posX=98, posY=50, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=2, worldY=32, posX=64, posY=60, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=2, worldY=32, posX=200, posY=38, posZ=1, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=3, worldY=32, posX=15, posY=18, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=3, worldY=31, posX=55, posY=294, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=32, posX=280, posY=280, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=3, worldY=33, posX=33, posY=57, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=32, posX=123, posY=262, posZ=1, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=13, worldY=35, posX=98, posY=254, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=13, worldY=37, posX=273, posY=29, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=13, worldY=38, posX=274, posY=169, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=12, worldY=38, posX=281, posY=187, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=12, worldY=36, posX=149, posY=194, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=11, worldY=36, posX=266, posY=103, posZ=1, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=11, worldY=36, posX=126, posY=105, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=11, worldY=36, posX=211, posY=83, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=11, worldY=36, posX=243, posY=206, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=11, worldY=36, posX=161, posY=248, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=11, worldY=37, posX=279, posY=69, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=45, posX=139, posY=233, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=9, worldY=46, posX=90, posY=97, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=46, posX=40, posY=61, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=44, posX=13, posY=237, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=7, worldY=46, posX=224, posY=177, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=46, posX=113, posY=255, posZ=1, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=47, posX=219, posY=76, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=47, posX=186, posY=267, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=48, posX=251, posY=63, posZ=1, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=10, worldY=48, posX=125, posY=169, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=47, posX=255, posY=275, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=5, worldY=48, posX=278, posY=249, posZ=2, town="Irvington", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=11, worldY=36, posX=95, posY=207, town="Echo Creek", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=2, worldY=32, posX=253, posY=119, posZ=1, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=13, posY=188, town="Fallas Lake", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=7, worldY=20, posX=52, posY=89, town="Brandenburg", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=32, posX=111, posY=161, town="Ekron", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
        { worldX=36, worldY=32, posX=176, posY=185, town="Muldraugh", type="Residential", cat="Home", hardcore=false, majorTown=true, balance=true, },
    }
    return points
end
