function RSL_SpawnPoints_NonRes_Louisville_B()
    local points = {
        { worldX=42, worldY=11, posX=9, posY=76, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=62, posY=221, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=82, posY=201, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=67, posY=180, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=59, posY=204, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=98, posY=116, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=281, posY=164, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=279, posY=145, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=29, posY=83, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=21, posY=80, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=240, posY=15, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=10, posX=277, posY=31, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=9, posX=221, posY=272, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=9, posX=275, posY=268, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=9, posX=281, posY=269, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=29, posY=266, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=30, posY=273, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=20, posY=276, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=20, posY=268, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=54, posY=282, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=28, posY=27, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=8, posY=49, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=19, posY=39, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=57, posY=26, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=83, posY=31, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=82, posY=16, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=151, posY=64, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=129, posY=49, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=118, posY=48, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=104, posY=56, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=112, posY=74, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=130, posY=72, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=173, posY=71, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=180, posY=79, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=199, posY=70, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=193, posY=54, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=185, posY=49, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=171, posY=48, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=95, posY=259, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=118, posY=265, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=132, posY=268, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=133, posY=258, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=133, posY=249, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=143, posY=238, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=182, posY=252, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=187, posY=230, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=256, posY=222, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=9, posX=281, posY=280, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=10, posX=251, posY=40, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=9, posY=91, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=31, posY=90, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=37, posY=93, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=52, posY=92, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=24, posY=23, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=31, posY=24, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=52, posY=24, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=64, posY=20, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=104, posY=23, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=95, posY=28, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=162, posY=260, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=161, posY=245, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=160, posY=230, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=159, posY=221, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=156, posY=211, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=160, posY=205, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=157, posY=192, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=146, posY=175, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=162, posY=165, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=146, posY=171, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=154, posY=154, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=152, posY=139, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=148, posY=135, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=152, posY=131, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=155, posY=144, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=150, posY=154, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=148, posY=122, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=154, posY=115, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=10, posX=157, posY=105, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=10, posX=95, posY=96, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=9, posX=96, posY=23, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=9, posX=83, posY=84, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=9, posX=75, posY=52, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=9, posX=194, posY=99, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=9, posX=203, posY=110, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=8, posX=181, posY=155, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=8, posX=280, posY=140, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=7, posX=148, posY=149, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=7, posX=147, posY=137, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=212, posY=181, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=197, posY=92, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=179, posY=65, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=6, posX=232, posY=97, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=190, posY=267, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=8, posX=30, posY=254, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=9, posX=155, posY=118, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=177, posY=182, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=163, posY=180, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=20, posY=4, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=56, posY=9, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=59, posY=21, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=54, posY=22, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=63, posY=62, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=58, posY=48, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=63, posY=40, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=55, posY=41, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=61, posY=12, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=60, posY=19, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=7, posX=60, posY=39, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=10, posY=42, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=33, posY=44, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=28, posY=20, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=57, posY=29, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=84, posY=46, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=7, posX=82, posY=36, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=76, posY=132, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=70, posY=135, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=96, posY=165, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=203, posY=279, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=88, posY=229, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=106, posY=215, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=82, posY=216, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=8, posX=174, posY=154, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=8, posX=234, posY=131, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=25, posY=278, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=10, posY=246, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=36, posY=251, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=23, posY=230, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=42, posY=189, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=19, posY=195, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=12, posY=177, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=69, posY=174, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=93, posY=182, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=80, posY=185, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=49, posY=140, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=71, posY=149, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=52, posY=148, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=39, posY=125, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=60, posY=129, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=61, posY=123, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=59, posY=109, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=56, posY=129, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=57, posY=122, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=66, posY=112, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=58, posY=89, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=64, posY=97, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=25, posY=105, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=23, posY=93, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=20, posY=82, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=26, posY=84, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=20, posY=82, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=16, posY=42, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=18, posY=64, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=24, posY=60, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=24, posY=46, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=62, posY=63, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=72, posY=44, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=69, posY=32, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=59, posY=13, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=50, posY=15, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=110, posY=122, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=143, posY=124, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=202, posY=121, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=199, posY=121, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=193, posY=81, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=179, posY=71, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=121, posY=83, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=120, posY=102, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=111, posY=48, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=108, posY=16, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=151, posY=8, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=7, posX=167, posY=8, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=131, posY=222, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=96, posY=214, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=97, posY=176, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=126, posY=170, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=277, posY=281, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=287, posY=283, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=281, posY=270, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=276, posY=253, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=176, posY=238, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=277, posY=225, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=282, posY=229, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=53, posY=269, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=29, posY=234, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=75, posY=222, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=74, posY=232, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=25, posY=243, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=189, posY=232, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=229, posY=226, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=160, posY=197, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=173, posY=197, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=217, posY=62, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=234, posY=74, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=228, posY=19, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=241, posY=24, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=7, posX=274, posY=22, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=170, posY=124, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=14, posY=43, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=38, posY=41, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=17, posY=109, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=6, posX=37, posY=114, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=190, posY=12, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=6, posX=185, posY=16, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=178, posY=202, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=175, posY=200, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=173, posY=209, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=183, posY=181, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=256, posY=215, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=238, posY=215, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=33, posY=171, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=45, posY=168, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=54, posY=169, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=40, worldY=5, posX=88, posY=192, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=160, posY=203, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=127, posY=221, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=211, posY=261, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=231, posY=275, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=232, posY=224, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=224, posY=174, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=217, posY=168, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=281, posY=267, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=273, posY=248, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=272, posY=240, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=275, posY=234, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=273, posY=224, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=281, posY=220, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=268, posY=215, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=262, posY=206, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=271, posY=198, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=272, posY=190, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=261, posY=179, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=276, posY=176, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=274, posY=166, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=50, posY=200, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=50, posY=188, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=51, posY=179, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=42, posY=178, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=47, posY=163, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=39, posY=157, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=49, posY=130, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=44, posY=150, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=147, posY=255, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=5, posX=140, posY=242, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=273, posY=143, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=269, posY=137, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=274, posY=130, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=270, posY=121, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=267, posY=112, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=276, posY=104, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=280, posY=92, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=266, posY=82, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=275, posY=75, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=270, posY=67, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=275, posY=57, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=273, posY=51, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=248, posY=16, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=269, posY=25, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=213, posY=11, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=216, posY=18, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=214, posY=23, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=219, posY=30, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=219, posY=41, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=214, posY=59, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=221, posY=67, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=215, posY=78, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=216, posY=91, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=215, posY=99, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=220, posY=104, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=246, posY=70, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=173, posY=136, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=57, posY=49, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=66, posY=45, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=68, posY=42, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=5, posX=112, posY=21, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=186, posY=22, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=169, posY=32, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=176, posY=41, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=183, posY=17, posZ=4, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=162, posY=27, posZ=5, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=180, posY=36, posZ=6, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=160, posY=113, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=169, posY=125, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=188, posY=134, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=167, posY=111, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=180, posY=129, posZ=4, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=170, posY=114, posZ=5, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=108, posY=107, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=107, posY=108, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=106, posY=110, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=124, posY=75, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=126, posY=71, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=5, posX=109, posY=23, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=151, posY=188, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=117, posY=178, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=118, posY=128, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=148, posY=131, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=159, posY=124, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=186, posY=125, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=180, posY=110, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=152, posY=63, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=147, posY=64, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=215, posY=167, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=225, posY=176, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=265, posY=197, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=275, posY=175, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=263, posY=131, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=286, posY=99, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=237, posY=101, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=213, posY=100, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=210, posY=127, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=232, posY=131, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=265, posY=97, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=215, posY=111, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=210, posY=95, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=289, posY=110, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=277, posY=101, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=289, posY=137, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=42, worldY=4, posX=226, posY=137, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=79, posY=82, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=29, posY=83, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=31, posY=88, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=23, posY=76, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=102, posY=84, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=77, posY=181, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=51, posY=178, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=6, posY=168, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=12, posY=199, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=6, posY=209, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=17, posY=239, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=13, posY=271, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=24, posY=283, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=32, posY=280, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=48, posY=282, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=61, posY=279, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=65, posY=245, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=80, posY=251, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=142, posY=272, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=153, posY=278, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=155, posY=279, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=175, posY=276, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=144, posY=277, posZ=4, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=150, posY=171, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=134, posY=221, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=116, posY=223, posZ=2, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=110, posY=189, posZ=3, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=219, posY=287, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=213, posY=277, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=219, posY=265, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=212, posY=257, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=215, posY=245, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=250, posY=248, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=253, posY=169, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=233, posY=116, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=10, posY=20, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=292, posY=37, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=290, posY=43, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=284, posY=54, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=290, posY=56, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=279, posY=63, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=286, posY=70, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=291, posY=76, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=288, posY=83, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=286, posY=93, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=294, posY=118, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=227, posY=153, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=22, posY=165, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=19, posY=181, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=22, posY=194, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=17, posY=201, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=45, posY=134, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=70, posY=78, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=60, posY=76, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=54, posY=82, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=46, posY=77, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=39, posY=81, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=30, posY=74, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=16, posY=82, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=7, posY=76, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=48, posY=16, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=58, posY=52, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=119, posY=42, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=119, posY=49, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=119, posY=53, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=133, posY=35, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=132, posY=50, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=109, posY=114, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=106, posY=102, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=123, posY=84, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=132, posY=90, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=148, posY=90, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=164, posY=88, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=99, posY=154, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=175, posY=152, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=204, posY=145, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=204, posY=158, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=279, posY=147, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=221, posY=91, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=231, posY=98, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=239, posY=90, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=257, posY=90, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=277, posY=110, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=266, posY=119, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=123, posY=165, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=112, posY=151, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=113, posY=138, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=115, posY=125, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=151, posY=124, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=165, posY=67, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=113, posY=67, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=105, posY=72, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=90, posY=65, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=76, posY=72, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=57, posY=72, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=44, posY=65, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=21, posY=64, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=17, posY=98, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=24, posY=115, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=24, posY=126, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=26, posY=155, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=27, posY=170, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=24, posY=180, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=64, posY=191, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=78, posY=162, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=69, posY=139, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=56, posY=162, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=30, posY=194, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=24, posY=196, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=19, posY=181, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=19, posY=148, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=18, posY=132, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=22, posY=97, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=36, posY=70, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=52, posY=66, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=74, posY=70, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=99, posY=63, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=116, posY=90, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=115, posY=108, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=118, posY=125, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=120, posY=151, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=116, posY=173, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=115, posY=191, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=79, posY=153, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=4, posX=65, posY=161, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=277, posY=207, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=219, posY=227, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=212, posY=274, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=4, posX=171, posY=224, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=24, posY=170, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=21, posY=210, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=90, posY=213, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=94, posY=201, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=82, posY=197, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=115, posY=204, posZ=3, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=98, posY=211, posZ=4, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=70, posY=198, posZ=4, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=99, posY=194, posZ=5, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=57, posY=166, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=54, posY=81, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=67, posY=79, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=73, posY=82, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=96, posY=42, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=85, posY=37, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=59, posY=37, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=50, posY=34, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=109, posY=23, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=110, posY=65, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=113, posY=104, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=193, posY=15, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=200, posY=6, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=176, posY=37, posZ=1, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=169, posY=41, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=173, posY=7, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=189, posY=70, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=158, posY=96, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=257, posY=89, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=5, posX=68, posY=187, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=165, posY=160, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=176, posY=228, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=174, posY=221, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=254, posY=289, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=220, posY=284, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=225, posY=281, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=5, posX=162, posY=266, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=46, worldY=11, posX=138, posY=225, town="Louisville", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=12, posX=20, posY=62, town="Louisville", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=11, posX=41, posY=190, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=11, posX=11, posY=215, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=44, worldY=11, posX=12, posY=226, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=52, worldY=10, posX=45, posY=278, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=266, posY=271, posZ=2, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=231, posY=285, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=208, posY=150, posZ=2, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=122, posY=255, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=7, posY=259, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=8, posY=168, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=8, posY=157, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=8, posY=131, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=51, posY=150, posZ=1, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=126, posY=175, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=130, posY=53, posZ=2, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=188, posY=79, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=10, posX=291, posY=78, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=9, posX=149, posY=166, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=9, posX=189, posY=149, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=9, posX=177, posY=212, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=9, posX=190, posY=199, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=9, posX=264, posY=166, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=9, posX=181, posY=160, posZ=3, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=9, posX=169, posY=230, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=8, posX=242, posY=79, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=8, posX=247, posY=92, posZ=1, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=8, posX=155, posY=89, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=8, posX=59, posY=280, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=51, worldY=8, posX=61, posY=269, posZ=8, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
    }
    return points
end
