function RSL_SpawnPoints_Balanced_NonResidential()
    local points = {
        { worldX=45, worldY=19, posX=72, posY=173, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=46, worldY=16, posX=170, posY=67, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=47, worldY=19, posX=10, posY=25, town="Valley Station", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=true, },
        { worldX=44, worldY=18, posX=60, posY=39, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=43, worldY=18, posX=195, posY=51, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=43, worldY=17, posX=109, posY=163, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=42, worldY=16, posX=249, posY=159, town="Valley Station", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=true, },
        { worldX=43, worldY=16, posX=47, posY=63, town="Valley Station", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=true, },
        { worldX=42, worldY=16, posX=142, posY=240, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=41, worldY=19, posX=270, posY=30, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=41, worldY=17, posX=240, posY=189, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=40, worldY=23, posX=62, posY=18, town="West Point", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=39, worldY=23, posX=287, posY=37, posZ=1, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=39, worldY=23, posX=178, posY=13, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=39, worldY=23, posX=128, posY=12, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=40, worldY=22, posX=67, posY=202, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=39, worldY=22, posX=207, posY=213, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=40, worldY=23, posX=127, posY=137, town="West Point", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=40, worldY=23, posX=71, posY=251, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=38, worldY=23, posX=263, posY=185, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=37, worldY=22, posX=281, posY=195, town="West Point", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=37, worldY=22, posX=254, posY=125, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=31, posX=133, posY=84, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=31, posX=110, posY=176, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=32, posX=107, posY=15, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=32, posX=133, posY=165, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=33, posX=107, posY=217, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=34, posX=111, posY=124, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=35, posX=119, posY=59, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=35, posX=173, posY=129, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=36, worldY=31, posX=39, posY=235, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=36, worldY=33, posX=40, posY=133, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=34, posX=265, posY=112, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=35, worldY=34, posX=203, posY=258, posZ=3, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=281, posY=220, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=268, posY=59, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=216, posY=181, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=263, posY=159, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=235, posY=150, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=209, posY=143, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=206, posY=112, town="March Ridge", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=175, posY=215, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=174, posY=175, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=128, posY=117, town="March Ridge", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=33, worldY=42, posX=96, posY=60, town="March Ridge", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=34, worldY=42, posX=128, posY=208, town="March Ridge", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=37, posX=267, posY=239, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=279, posY=55, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=221, posY=29, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=197, posY=52, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=284, posY=158, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=292, posY=208, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=26, worldY=38, posX=277, posY=264, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=27, worldY=37, posX=80, posY=169, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=27, worldY=37, posX=52, posY=238, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=27, worldY=38, posX=42, posY=100, town="Rosewood", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=27, worldY=39, posX=33, posY=48, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=27, worldY=38, posX=250, posY=202, town="Rosewood", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=103, posY=97, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=35, posY=108, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=96, posY=155, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=95, posY=201, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=49, posY=185, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=56, posY=229, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=94, posY=234, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=93, posY=290, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=28, posX=57, posY=32, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=28, posX=60, posY=100, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=28, posX=50, posY=125, town="Fallas Lake", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=24, worldY=27, posX=193, posY=254, town="Fallas Lake", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=22, worldY=17, posX=137, posY=143, town="Riverside", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=21, worldY=17, posX=257, posY=210, posZ=5, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=21, worldY=17, posX=90, posY=207, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=21, worldY=17, posX=82, posY=105, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=20, worldY=17, posX=241, posY=166, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=20, worldY=17, posX=141, posY=273, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=19, worldY=17, posX=219, posY=144, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=19, worldY=17, posX=257, posY=291, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=21, worldY=18, posX=164, posY=39, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=18, worldY=19, posX=142, posY=214, town="Riverside", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=18, worldY=19, posX=18, posY=172, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=18, worldY=19, posX=31, posY=271, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=40, worldY=10, posX=227, posY=28, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=40, worldY=8, posX=170, posY=248, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=41, worldY=5, posX=115, posY=256, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=40, worldY=4, posX=268, posY=111, town="Louisville", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=42, worldY=4, posX=141, posY=8, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=41, worldY=8, posX=283, posY=10, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=43, worldY=10, posX=10, posY=39, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=46, worldY=10, posX=138, posY=49, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=45, worldY=8, posX=177, posY=140, town="Louisville", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=43, worldY=5, posX=18, posY=170, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=44, worldY=4, posX=26, posY=80, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=45, worldY=5, posX=178, posY=245, town="Louisville", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=20, posX=294, posY=24, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=19, posX=238, posY=140, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=21, posX=127, posY=282, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=19, posX=28, posY=243, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=18, posX=258, posY=288, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=5, worldY=19, posX=50, posY=51, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=7, worldY=19, posX=138, posY=41, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=19, posX=275, posY=245, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=21, posX=264, posY=14, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=21, posX=154, posY=82, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=21, posX=40, posY=95, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=21, posX=12, posY=124, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=2, worldY=32, posX=180, posY=170, town="Ekron", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=2, worldY=32, posX=128, posY=246, town="Ekron", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=2, worldY=32, posX=84, posY=255, town="Ekron", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=2, worldY=32, posX=8, posY=249, town="Ekron", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=2, worldY=33, posX=69, posY=21, town="Ekron", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=32, posX=125, posY=258, town="Ekron", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=32, posX=107, posY=263, town="Ekron", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=33, posX=161, posY=33, town="Ekron", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=32, posX=141, posY=230, town="Ekron", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=32, posX=134, posY=192, town="Ekron", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=1, worldY=32, posX=161, posY=181, town="Ekron", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=12, worldY=36, posX=88, posY=99, posZ=1, town="Echo Creek", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=12, worldY=36, posX=11, posY=156, town="Echo Creek", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=11, worldY=36, posX=134, posY=152, town="Echo Creek", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=11, worldY=37, posX=237, posY=121, town="Echo Creek", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=11, worldY=38, posX=156, posY=111, posZ=1, town="Echo Creek", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=7, worldY=46, posX=281, posY=134, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=46, posX=78, posY=259, posZ=1, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=46, posX=74, posY=221, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=46, posX=133, posY=263, town="Irvington", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=46, posX=119, posY=283, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=10, worldY=48, posX=75, posY=61, town="Irvington", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=7, worldY=48, posX=271, posY=74, town="Irvington", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=47, posX=62, posY=222, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=8, worldY=47, posX=19, posY=152, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=true, },
        { worldX=6, worldY=48, posX=222, posY=260, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=5, worldY=49, posX=260, posY=84, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=12, worldY=48, posX=178, posY=268, posZ=1, town="Irvington", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=true, },
        { worldX=42, worldY=21, posX=66, posY=116, posZ=2, town="Valley Station", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=11, worldY=36, posX=273, posY=99, town="Echo Creek", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=39, worldY=22, posX=203, posY=265, town="West Point", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=true, },
        { worldX=12, worldY=36, posX=9, posY=105, town="Echo Creek", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=true, },
        { worldX=11, worldY=36, posX=97, posY=142, town="Echo Creek", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=true, },
        { worldX=11, worldY=36, posX=132, posY=181, town="Echo Creek", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=true, },
        { worldX=12, worldY=37, posX=53, posY=254, town="Echo Creek", type="NonResidential", cat="Farm", hardcore=false, majorTown=false, balance=true, },
        { worldX=12, worldY=36, posX=184, posY=284, town="Echo Creek", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=true, },
        { worldX=12, worldY=36, posX=184, posY=140, town="Echo Creek", type="NonResidential", cat="Farm", hardcore=false, majorTown=false, balance=true, },
        { worldX=1, worldY=31, posX=209, posY=170, town="Ekron", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=true, },
    }
    return points
end
