function RSL_SpawnPoints_NonRes_Other_B()
    local points = {
        { worldX=21, worldY=17, posX=64, posY=213, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=63, posY=202, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=48, posY=197, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=209, posY=161, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=195, posY=166, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=193, posY=159, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=184, posY=166, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=174, posY=170, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=176, posY=159, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=151, posY=163, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=137, posY=159, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=137, posY=164, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=123, posY=164, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=118, posY=170, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=104, posY=168, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=105, posY=159, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=108, posY=153, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=95, posY=104, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=65, posY=168, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=40, posY=158, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=40, posY=158, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=74, posY=151, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=17, posX=10, posY=167, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=273, posY=165, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=274, posY=160, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=267, posY=159, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=261, posY=170, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=252, posY=164, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=118, posY=206, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=131, posY=212, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=81, posY=164, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=59, posY=205, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=17, posX=256, posY=165, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=17, posX=255, posY=162, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=17, posX=271, posY=262, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=17, posX=273, posY=291, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=18, posX=263, posY=16, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=18, posX=94, posY=26, town="Riverside", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=17, posX=8, posY=247, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=18, posX=129, posY=40, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=18, posX=125, posY=24, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=18, posX=143, posY=66, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=18, posX=152, posY=50, town="Riverside", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=19, posX=157, posY=234, town="Riverside", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=19, posX=165, posY=210, town="Riverside", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=19, posX=206, posY=196, town="Riverside", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=19, posX=218, posY=208, town="Riverside", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=19, posX=217, posY=202, town="Riverside", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=20, posX=115, posY=87, town="Riverside", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=19, posX=25, posY=210, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=19, posX=20, posY=222, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=19, posX=28, posY=262, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=21, posX=36, posY=155, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=21, posX=24, posY=146, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=21, posX=66, posY=119, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=21, posX=54, posY=122, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=21, posX=78, posY=161, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=21, posX=51, posY=155, posZ=1, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=21, posX=47, posY=155, posZ=1, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=21, posX=52, posY=127, posZ=1, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=21, posX=289, posY=222, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=21, posX=263, posY=222, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=21, posX=176, posY=76, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=21, posX=184, posY=79, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=24, posX=183, posY=171, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=33, worldY=24, posX=194, posY=152, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=24, posX=7, posY=215, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=24, posX=55, posY=73, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=24, posX=158, posY=218, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=34, worldY=24, posX=134, posY=210, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=23, posX=76, posY=288, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=23, posX=85, posY=245, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=23, posX=161, posY=289, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=24, posX=242, posY=126, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=23, posX=239, posY=99, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=23, posX=277, posY=233, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=23, posX=82, posY=253, town="West Point", type="NonResidential", cat="House", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=23, posX=82, posY=240, town="West Point", type="NonResidential", cat="House", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=23, posX=103, posY=240, town="West Point", type="NonResidential", cat="House", hardcore=false, majorTown=true, balance=false, },
        { worldX=37, worldY=22, posX=35, posY=252, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=22, posX=142, posY=124, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=22, posX=96, posY=75, town="West Point", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=45, worldY=15, posX=68, posY=114, town="Valley Station", type="NonResidential", cat="Farm", hardcore=false, majorTown=false, balance=false, },
        { worldX=45, worldY=15, posX=106, posY=290, town="Valley Station", type="NonResidential", cat="Farm", hardcore=false, majorTown=false, balance=false, },
        { worldX=46, worldY=15, posX=45, posY=237, town="Valley Station", type="NonResidential", cat="Farm", hardcore=false, majorTown=false, balance=false, },
        { worldX=47, worldY=16, posX=148, posY=41, town="Valley Station", type="NonResidential", cat="Farm", hardcore=false, majorTown=false, balance=false, },
        { worldX=47, worldY=15, posX=295, posY=58, town="Valley Station", type="NonResidential", cat="Farm", hardcore=false, majorTown=false, balance=false, },
        { worldX=47, worldY=17, posX=206, posY=53, town="Valley Station", type="NonResidential", cat="Farm", hardcore=false, majorTown=false, balance=false, },
        { worldX=47, worldY=16, posX=220, posY=161, town="Valley Station", type="NonResidential", cat="Farm", hardcore=false, majorTown=false, balance=false, },
        { worldX=47, worldY=18, posX=245, posY=49, town="Valley Station", type="NonResidential", cat="Farm", hardcore=false, majorTown=false, balance=false, },
        { worldX=19, worldY=19, posX=18, posY=26, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=18, posX=45, posY=125, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=18, posX=10, posY=46, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=18, posX=86, posY=119, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=16, worldY=18, posX=129, posY=205, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=16, worldY=19, posX=41, posY=37, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=15, worldY=19, posX=242, posY=29, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=15, worldY=19, posX=130, posY=203, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=15, worldY=19, posX=39, posY=27, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=14, worldY=19, posX=50, posY=31, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=14, worldY=19, posX=202, posY=57, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=15, worldY=19, posX=8, posY=5, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=13, worldY=19, posX=211, posY=186, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=13, worldY=19, posX=170, posY=140, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=13, worldY=19, posX=52, posY=82, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=19, posX=147, posY=190, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=20, posX=264, posY=126, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=20, posX=251, posY=83, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=20, posX=189, posY=275, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=20, posX=138, posY=240, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=21, posX=202, posY=239, town="Riverside", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=23, posX=254, posY=283, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=28, worldY=28, posX=163, posY=95, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=28, worldY=29, posX=216, posY=123, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=29, worldY=30, posX=14, posY=280, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=28, worldY=31, posX=112, posY=62, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=28, worldY=31, posX=157, posY=137, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=31, posX=163, posY=91, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=31, posX=184, posY=120, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=23, worldY=30, posX=213, posY=159, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=29, posX=213, posY=174, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=23, worldY=31, posX=45, posY=53, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=29, posX=53, posY=243, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=29, posX=15, posY=147, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=31, posX=118, posY=102, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=30, posX=210, posY=136, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=30, posX=210, posY=175, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=31, posX=210, posY=35, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=21, worldY=31, posX=175, posY=52, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=31, posX=129, posY=99, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=31, posX=268, posY=82, town="Fallas Lake", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=35, posX=227, posY=62, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=34, posX=188, posY=288, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=34, posX=233, posY=113, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=34, posX=262, posY=35, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=17, worldY=33, posX=155, posY=225, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=33, posX=131, posY=77, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=32, posX=170, posY=281, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=18, worldY=32, posX=168, posY=282, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=32, posX=268, posY=279, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=32, posX=268, posY=254, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=32, posX=114, posY=23, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=32, posX=173, posY=5, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=19, worldY=31, posX=258, posY=293, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=31, posX=85, posY=288, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=20, worldY=31, posX=119, posY=254, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=33, posX=200, posY=46, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=33, posX=210, posY=28, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=33, posX=205, posY=8, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=33, posX=213, posY=262, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=22, worldY=33, posX=178, posY=235, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=23, worldY=32, posX=243, posY=20, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=23, worldY=32, posX=262, posY=82, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=32, posX=20, posY=106, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=23, worldY=32, posX=271, posY=137, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=32, posX=141, posY=237, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=32, posX=194, posY=277, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=34, posX=97, posY=36, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=34, posX=69, posY=48, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=34, posX=44, posY=33, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=34, posX=29, posY=45, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=33, posX=223, posY=260, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=33, posX=110, posY=284, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=33, posX=81, posY=285, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=33, posX=207, posY=233, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=35, posX=40, posY=48, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=23, worldY=35, posX=19, posY=94, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=23, worldY=35, posX=32, posY=87, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=23, worldY=35, posX=75, posY=127, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=35, posX=85, posY=236, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=35, posX=137, posY=264, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=36, posX=275, posY=25, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=24, worldY=36, posX=96, posY=67, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=37, posX=179, posY=22, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=25, worldY=36, posX=172, posY=269, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=36, posX=171, posY=273, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=36, posX=186, posY=238, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=39, posX=216, posY=200, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=39, posX=10, posY=213, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=40, posX=38, posY=41, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=40, posX=182, posY=75, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=40, posX=124, posY=154, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=26, worldY=41, posX=182, posY=43, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=27, worldY=40, posX=15, posY=224, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=30, worldY=40, posX=162, posY=151, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=29, worldY=40, posX=251, posY=122, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=29, worldY=40, posX=201, posY=71, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=29, worldY=38, posX=109, posY=196, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=29, worldY=38, posX=155, posY=206, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=30, worldY=39, posX=128, posY=119, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=30, worldY=39, posX=140, posY=101, town="Rosewood", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=30, posX=24, posY=72, town="Muldraugh", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=36, worldY=29, posX=36, posY=245, town="Muldraugh", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=38, worldY=29, posX=150, posY=156, town="Dixie", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=70, posY=111, town="Dixie", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=108, posY=141, town="Dixie", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=268, posY=96, town="Dixie", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=283, posY=123, town="Dixie", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=27, posX=194, posY=209, town="Dixie", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=27, posX=266, posY=205, town="Dixie", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=222, posY=176, town="Dixie", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=29, posX=290, posY=90, town="Dixie", type="NonResidential", cat="Industrial", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=27, posX=286, posY=263, town="Dixie", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=38, worldY=27, posX=210, posY=151, town="Dixie", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=6, worldY=19, posX=279, posY=187, posZ=1, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=19, posX=281, posY=204, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=19, posX=275, posY=274, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=19, posX=294, posY=77, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=19, posX=237, posY=211, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=19, posX=230, posY=283, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=20, posX=267, posY=177, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=20, posX=260, posY=199, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=20, posX=267, posY=263, posZ=1, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=21, posX=35, posY=123, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=21, posX=262, posY=120, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=21, posX=210, posY=53, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=21, posX=202, posY=129, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=21, posX=236, posY=189, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=21, posX=183, posY=255, town="Brandenburg", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=21, posX=193, posY=51, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=21, posX=36, posY=115, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=19, posX=121, posY=61, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=4, worldY=19, posX=231, posY=144, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=3, worldY=18, posX=277, posY=21, posZ=1, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=3, worldY=18, posX=276, posY=34, posZ=1, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=19, posX=93, posY=81, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=19, posX=102, posY=78, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=21, posX=275, posY=81, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=19, posX=242, posY=120, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=19, posX=268, posY=259, posZ=-1, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=19, posX=274, posY=268, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=21, posX=275, posY=81, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=21, posX=146, posY=49, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=21, posX=108, posY=32, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=21, posX=115, posY=132, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=22, posX=168, posY=61, town="Brandenburg", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=4, worldY=19, posX=211, posY=199, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=3, worldY=20, posX=38, posY=162, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=4, worldY=24, posX=20, posY=182, posZ=1, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=4, worldY=24, posX=19, posY=194, town="Brandenburg", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=29, posX=130, posY=140, town="Ekron", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=30, posX=52, posY=270, posZ=1, town="Ekron", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=30, posX=170, posY=54, town="Ekron", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=3, worldY=30, posX=86, posY=59, town="Ekron", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=0, worldY=29, posX=101, posY=258, town="Ekron", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=2, worldY=32, posX=158, posY=182, town="Ekron", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=2, worldY=32, posX=178, posY=183, posZ=-1, town="Ekron", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=2, worldY=32, posX=146, posY=250, town="Ekron", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=2, worldY=32, posX=168, posY=221, posZ=3, town="Ekron", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=2, worldY=32, posX=219, posY=277, town="Ekron", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=1, worldY=32, posX=221, posY=257, town="Ekron", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=1, worldY=32, posX=143, posY=238, town="Ekron", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=1, worldY=32, posX=146, posY=194, town="Ekron", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=1, worldY=32, posX=154, posY=191, town="Ekron", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=14, worldY=32, posX=88, posY=121, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=10, worldY=40, posX=169, posY=134, town="Echo Creek", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=36, posX=220, posY=31, town="Echo Creek", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=36, posX=176, posY=8, town="Echo Creek", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=35, posX=223, posY=217, town="Echo Creek", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=9, worldY=42, posX=248, posY=192, town="Echo Creek", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=3, worldY=43, posX=128, posY=97, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=3, worldY=43, posX=131, posY=86, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=3, worldY=43, posX=75, posY=173, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=2, worldY=43, posX=277, posY=76, posZ=2, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=2, worldY=43, posX=281, posY=191, posZ=3, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=10, worldY=44, posX=242, posY=284, town="Irvington", type="NonResidential", cat="Farm", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=35, posY=96, town="Irvington", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=88, posY=145, posZ=1, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=30, posY=182, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=51, posY=283, posZ=1, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=76, posY=260, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=119, posY=228, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=122, posY=253, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=124, posY=264, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=158, posY=39, town="Irvington", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=10, worldY=48, posX=48, posY=154, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=10, worldY=48, posX=118, posY=70, posZ=1, town="Irvington", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=9, worldY=48, posX=219, posY=65, town="Irvington", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=181, posY=71, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=143, posY=66, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=136, posY=69, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=127, posY=66, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=157, posY=153, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=169, posY=153, posZ=1, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=83, posY=65, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=83, posY=60, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=74, posY=67, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=67, posY=61, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=62, posY=67, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=44, posY=137, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=48, posX=12, posY=132, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=48, posX=277, posY=133, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=7, worldY=48, posX=208, posY=82, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=8, worldY=47, posX=31, posY=137, town="Irvington", type="NonResidential", cat="Civic", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=49, posX=68, posY=153, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=49, posX=24, posY=156, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=49, posX=62, posY=68, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=49, posX=41, posY=64, posZ=1, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=6, worldY=49, posX=26, posY=76, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=49, posX=253, posY=81, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=49, posX=241, posY=103, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=5, worldY=49, posX=264, posY=188, town="Irvington", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=12, worldY=48, posX=233, posY=14, town="Irvington", type="NonResidential", cat="Industrial", hardcore=false, majorTown=true, balance=false, },
        { worldX=28, worldY=48, posX=167, posY=21, town="Hog Wallow", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=28, worldY=48, posX=130, posY=31, posZ=2, town="Hog Wallow", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=28, worldY=48, posX=97, posY=33, posZ=3, town="Hog Wallow", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=29, worldY=47, posX=5, posY=69, town="Hog Wallow", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=29, worldY=46, posX=26, posY=279, town="Hog Wallow", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=11, worldY=27, posX=178, posY=111, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=11, worldY=27, posX=156, posY=84, posZ=1, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=11, worldY=27, posX=212, posY=137, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=false, majorTown=false, balance=false, },
        { worldX=20, worldY=17, posX=71, posY=223, town="Riverside", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
        { worldX=35, worldY=32, posX=130, posY=55, town="Muldraugh", type="NonResidential", cat="Business", hardcore=false, majorTown=true, balance=false, },
    }
    return points
end
