function RSL_SpawnPoints_Hardcore()
    return {
        -- Brandenburg
        { worldX= 6, worldY=19, posX=231, posY=277, town="Brandenburg", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Brandenburg Police Station Jail Cell ID:2427,
        { worldX= 6, worldY=20, posX=153, posY=142, town="Brandenburg", type="NonResidential", cat="Civic", cat2="Misc", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Brandenburg Tornado Shelter ID:2468,
        { worldX= 7, worldY=21, posX=136, posY=104, posZ=-2, town="Brandenburg", type="NonResidential", cat="Business", cat2="Vacant", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Brandenburg Basement Morgue ID:2478,
        -- Doe Valley Forest
        { worldX=18, worldY=32, posX= 76, posY=114, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Service", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- gas station ID:629,
        { worldX=18, worldY=32, posX= 71, posY= 80, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Service", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- laundromat ID:630,
        { worldX=18, worldY=32, posX= 71, posY= 68, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Mechanic", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- autoshop lobby ID:631,
        { worldX=18, worldY=32, posX= 70, posY= 58, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Mechanic", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- autoshop workfloor ID:632,
        { worldX=18, worldY=32, posX= 39, posY= 83, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Office", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- offices ID:633,
        { worldX=18, worldY=31, posX= 67, posY=285, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Shopping", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- grocery store ID:634,
        { worldX=18, worldY=31, posX= 63, posY=279, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Dining", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- grocery store, kitchen 1 ID:635,
        { worldX=18, worldY=31, posX= 59, posY=269, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Dining", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- grocery store, kitchen 2 ID:636,
        { worldX=18, worldY=31, posX= 97, posY=286, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Medical", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- dr office lobby ID:637,
        { worldX=18, worldY=31, posX=103, posY=280, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Medical", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- dr office exam room ID:638,
        { worldX=18, worldY=31, posX=100, posY=266, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Shopping", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- clothing store ID:639,
        { worldX=12, worldY=28, posX=201, posY=153, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Shopping", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- camping store ID:640,
        { worldX=12, worldY=28, posX=208, posY=114, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Shopping", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- gun shop ID:641,
        { worldX=12, worldY=28, posX= 92, posY= 98, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Service", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- gas station ID:642,
        { worldX=12, worldY=28, posX=104, posY= 69, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Dining", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- diner ID:643,
        { worldX=12, worldY=28, posX=103, posY= 62, town="Doe Valley Forest", type="NonResidential", cat="Business", cat2="Dining", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- diner, kitchen ID:644,
        { worldX=12, worldY=28, posX= 46, posY=166, town="Doe Valley Forest", type="Residential", cat="Home", cat2="Home", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- medium house ID:645,
        { worldX=13, worldY=21, posX=243, posY=108, town="Doe Valley Forest", type="NonResidential", cat="Civic", cat2="Vacant", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Waverly Hills Sanatorium Room 1 ID:2402,
        { worldX=13, worldY=21, posX=204, posY=108, town="Doe Valley Forest", type="NonResidential", cat="Civic", cat2="Vacant", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Waverly Hills Sanatorium Room 2 ID:2403,
        { worldX=13, worldY=21, posX=208, posY=185, town="Doe Valley Forest", type="NonResidential", cat="Civic", cat2="Vacant", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Waverly Hills Sanatorium Room 3 ID:2404,
        { worldX=13, worldY=21, posX=180, posY=216, posZ=2, town="Doe Valley Forest", type="NonResidential", cat="Civic", cat2="Vacant", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Waverly Hills Sanatorium Room 4 ID:2405,
        { worldX=13, worldY=21, posX=186, posY=227, town="Doe Valley Forest", type="NonResidential", cat="Civic", cat2="Vacant", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Waverly Hills Sanatorium Kitchen ID:2406,
        { worldX=13, worldY=21, posX=210, posY=224, town="Doe Valley Forest", type="NonResidential", cat="Civic", cat2="Vacant", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Waverly Hills Creepiest Room ID:2407,
        { worldX= 9, worldY=30, posX=191, posY= 52, posZ=1, town="Doe Valley Forest", type="NonResidential", cat="Civic", cat2="Remote", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Doe Valley Abandoned Boarding School Room ID:2529,
        { worldX= 9, worldY=30, posX=187, posY= 92, posZ=1, town="Doe Valley Forest", type="NonResidential", cat="Civic", cat2="Remote", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Doe Valley Abandoned Boarding School  Kitchen ID:2530,
        { worldX=18, worldY=31, posX=176, posY= 65, posZ=-1, town="Doe Valley Forest", type="Residential", cat="Home", cat2="Remote", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Doe Valley Bunker ID:2687,
        -- Echo Creek
        { worldX=11, worldY=32, posX= 71, posY= 88, town="Echo Creek", type="NonResidential", cat="Industrial", cat2="Remote", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Forestry  Office ID:2539,
        { worldX= 7, worldY=37, posX= 66, posY=118, town="Echo Creek", type="NonResidential", cat="Cabin", cat2="Remote", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Echo Creek Wilderness House ID:2566,
        { worldX= 8, worldY=36, posX=164, posY= 95, posZ=1, town="Echo Creek", type="NonResidential", cat="Industrial", cat2="Factory", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Gun Factory Office ID:2567,
        { worldX=12, worldY=41, posX=219, posY=239, town="Echo Creek", type="NonResidential", cat="Cabin", cat2="Remote", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Echo Creek Prepper House ID:2688,
        -- Ekron
        { worldX= 6, worldY=28, posX=179, posY=201, town="Ekron", type="Residential", cat="Home", cat2="Remote", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Ekron Lake house ID:2489,
        -- Fallas Lake
        { worldX=24, worldY=27, posX= 53, posY=278, town="Fallas Lake", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- police station, jail ID:493,
        { worldX=21, worldY=25, posX= 67, posY=120, posZ=2, town="Fallas Lake", type="NonResidential", cat="Cabin", cat2="Remote", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Fallas Lake remote Luxury cabins ID:2690,
        -- Hog Wallow
        { worldX=19, worldY=48, posX= 15, posY=160, town="Hog Wallow", type="NonResidential", cat="Cabin", cat2="Remote", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Hog wallow camping office ID:2668,
        { worldX=26, worldY=48, posX= 83, posY=222, town="Hog Wallow", type="NonResidential", cat="Cabin", cat2="Remote", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Hog Wallow Wilderness House ID:2670,
        { worldX=27, worldY=49, posX= 17, posY=203, town="Hog Wallow", type="NonResidential", cat="Cabin", cat2="Remote", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Camp Arthur Wildnrness abandoned church ID:2676,
        { worldX=26, worldY=50, posX=215, posY=285, town="Hog Wallow", type="NonResidential", cat="Industrial", cat2="Remote", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Wastewater plant reception ID:2677,
        { worldX=28, worldY=50, posX=241, posY= 53, posZ=1, town="Hog Wallow", type="NonResidential", cat="Cabin", cat2="Remote", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Hog Wallow Island Cabin 1 ID:2678,
        { worldX=28, worldY=50, posX=259, posY=262, town="Hog Wallow", type="NonResidential", cat="Cabin", cat2="Remote", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Hog Wallow Island Cabin 2 ID:2679,
        -- Irvington
        { worldX= 8, worldY=46, posX= 89, posY=136, posZ=1, town="Irvington", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Irvington Police Jail Cell ID:2594,
        -- Isolated Areas
        { worldX=33, worldY=22, posX=283, posY=165, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Cabin by the Lake, West of West Point ID:652,
        { worldX=45, worldY=24, posX=132, posY= 24, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Cabin east of West Point ID:653,
        { worldX=32, worldY=29, posX= 67, posY= 75, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Forest Cabin, Western Woods ID:654,
        { worldX=37, worldY=29, posX=142, posY=254, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Forest Cabin, near Dixie ID:655,
        { worldX=14, worldY=24, posX= 47, posY= 28, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Extremely Isolated Camping cabin ID:656,
        { worldX=38, worldY=30, posX=180, posY=290, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Isolated Forest House ID:657,
        { worldX=31, worldY=34, posX= 45, posY= 96, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Forest Shack between Rosewood and Muldraugh ID:658,
        { worldX=41, worldY=29, posX=173, posY=220, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Muldraugh Campgrounds ID:659,
        { worldX=15, worldY=28, posX=175, posY=202, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Greeting Hall 1, south of lake ID:660,
        { worldX=16, worldY=26, posX=211, posY=196, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Greeting Hall 2, east of lake ID:661,
        { worldX=16, worldY=26, posX=211, posY=196, posZ=1, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Greeting Hall 2, east of lake, 2nd f ID:662,
        { worldX=16, worldY=26, posX=102, posY=137, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp utility building ID:663,
        { worldX=15, worldY=26, posX=223, posY=190, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp dining hall ID:664,
        { worldX=15, worldY=26, posX=216, posY=194, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp dining hall, kitchen ID:665,
        { worldX=13, worldY=27, posX=165, posY= 52, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp dining hall, ranger cabin ID:666,
        { worldX=15, worldY=26, posX=210, posY= 47, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Cabins, S1 ID:667,
        { worldX=15, worldY=26, posX=222, posY= 47, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Cabins, S2 ID:668,
        { worldX=15, worldY=26, posX=266, posY= 47, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Cabins, S3 ID:669,
        { worldX=15, worldY=26, posX=278, posY= 47, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Cabins, S4 ID:670,
        { worldX=15, worldY=26, posX=210, posY= 19, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Cabins, N1 ID:671,
        { worldX=15, worldY=26, posX=222, posY= 19, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Cabins, N2 ID:672,
        { worldX=15, worldY=26, posX=266, posY= 19, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Cabins, N3 ID:673,
        { worldX=15, worldY=26, posX=278, posY= 19, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Cabins, N4 ID:674,
        { worldX=16, worldY=26, posX=211, posY=197, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Cabins, admin building ID:677,
        { worldX=15, worldY=26, posX=207, posY=116, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- Scouting Camp Cabins, nice cabin ID:678,
        { worldX=36, worldY=35, posX=265, posY=142, town="Isolated Areas", type="NonResidential", cat="Cabin", cat2="Camp", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- South Muldraugh Cabin ID:679,
        -- Louisville
        { worldX=40, worldY=12, posX=232, posY= 33, town="Louisville", type="Residential", cat="Home", cat2="Vacant", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- LV River house, construction ID:999,
        { worldX=41, worldY= 5, posX=130, posY=101, town="Louisville", type="NonResidential", cat="Civic", cat2="Police", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Louisville Police Department and Jail, breakroom ID:1313,
        { worldX=41, worldY= 5, posX=114, posY= 89, town="Louisville", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Louisville Police Department and Jail, cell 1 ID:1314,
        { worldX=43, worldY= 4, posX= 55, posY=190, town="Louisville", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- c louisville police station, jail clel ID:2150,
        -- Muldraugh
        { worldX=38, worldY=34, posX=212, posY=  1, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Security", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard security office ID:195,
        { worldX=38, worldY=33, posX=189, posY=220, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Storage", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard depot 1 ID:196,
        { worldX=38, worldY=33, posX=264, posY=195, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Storage", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard depot 2 ID:197,
        { worldX=38, worldY=33, posX=204, posY=143, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Storage", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard depot 3 ID:198,
        { worldX=38, worldY=33, posX=264, posY=124, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Storage", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard depot 4 ID:199,
        { worldX=39, worldY=33, posX=  5, posY= 31, posZ=2, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Transport", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard station 1 ID:200,
        { worldX=38, worldY=32, posX=283, posY=222, posZ=3, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Transport", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard station 2 ID:201,
        { worldX=38, worldY=32, posX=200, posY=213, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Transport", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard station 3 ID:202,
        { worldX=38, worldY=33, posX=129, posY=117, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Office", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard big office 1 ID:203,
        { worldX=38, worldY=33, posX=158, posY= 79, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Dining", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard cafeteria ID:204,
        { worldX=38, worldY=33, posX=163, posY= 36, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Office", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard small office ID:205,
        { worldX=38, worldY=32, posX=130, posY= 54, posZ=2, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Office", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- railyard big office 2 ID:206,
        { worldX=39, worldY=32, posX=127, posY=183, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Storage", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- empty warehouse 1, east of railyard, storage floor ID:207,
        { worldX=39, worldY=32, posX=104, posY=179, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Storage", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- empty warehouse 1, east of railyard, breakroom ID:208,
        { worldX=39, worldY=32, posX=127, posY=183, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Storage", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- empty warehouse 2, east of railyard, storage floor ID:209,
        { worldX=39, worldY=32, posX=199, posY=220, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Storage", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- empty warehouse 2, east of railyard, breakroom ID:210,
        { worldX=35, worldY=34, posX=134, posY=208, town="Muldraugh", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- police station, jail ID:278,
        { worldX=34, worldY=29, posX= 53, posY= 34, town="Muldraugh", type="NonResidential", cat="Industrial", cat2="Remote", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Muldraugh Radio Tower ID:2689,
        { worldX=33, worldY=27, posX=186, posY=161, posZ=1, town="Muldraugh", type="NonResidential", cat="Farm", cat2="Remote", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- B42 House ID:2695,
        { worldX=42, worldY=29, posX=115, posY= 47, town="Muldraugh", type="NonResidential", cat="Cabin", cat2="Remote", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Muldraugh Nice Remote Cabin ID:2727,
        -- Riverside
        { worldX=20, worldY=17, posX= 82, posY=158, town="Riverside", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- police station, jail ID:563,
        { worldX=16, worldY=20, posX= 33, posY=279, town="Riverside", type="NonResidential", cat="Industrial", cat2="Remote", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- Riverside Radio Tower ID:2700,
        -- Rosewood
        { worldX=26, worldY=39, posX=251, posY= 48, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- police station, jail ID:430,
        { worldX=25, worldY=39, posX=183, posY=130, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- cell 1, north block ID:472,
        { worldX=25, worldY=39, posX=196, posY=127, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- cell 2, north block ID:473,
        { worldX=25, worldY=39, posX=187, posY=147, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- north block floor ID:474,
        { worldX=25, worldY=39, posX=181, posY=240, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- cell 3, south block ID:475,
        { worldX=25, worldY=39, posX=196, posY=225, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- cell 4, south block ID:476,
        { worldX=25, worldY=39, posX=188, posY=215, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- south block floor ID:477,
        { worldX=25, worldY=39, posX=183, posY=210, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- cell 5, south block ID:648,
        { worldX=25, worldY=39, posX=183, posY=231, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- cell 6, south block ID:649,
        { worldX=25, worldY=39, posX=183, posY=234, posZ=1, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- cell 7, south block ID:650,
        { worldX=25, worldY=39, posX=197, posY=234, posZ=1, town="Rosewood", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- cell 8, south block ID:651,
        -- Valley Station
        { worldX=48, worldY=16, posX=150, posY=178, town="Valley Station", type="NonResidential", cat="Civic", cat2="Misc", hardcore=true, majorTown=false, balance=false, wilderness=false }, -- graveyard ID:37,
        -- West Point
        { worldX=39, worldY=23, posX=188, posY= 48, posZ=2, town="West Point", type="NonResidential", cat="Civic", cat2="Jail", hardcore=true, majorTown=true, balance=false, wilderness=false }, -- police station, jail ID:109,
    }
end
