function RSL_SpawnPoints_Hardcore()
    local points = {
        { worldX=48, worldY=16, posX=150, posY=178, town="Valley Station", type="NonResidential", cat="Civic", hardcore=true, majorTown=false, balance=false, },
        { worldX=39, worldY=23, posX=188, posY=48, posZ=2, town="West Point", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=34, posX=212, posY=1, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=33, posX=189, posY=220, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=33, posX=264, posY=195, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=33, posX=204, posY=143, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=33, posX=264, posY=124, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=39, worldY=33, posX=5, posY=31, posZ=2, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=32, posX=283, posY=222, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=32, posX=200, posY=213, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=33, posX=129, posY=117, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=33, posX=158, posY=79, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=33, posX=163, posY=36, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=38, worldY=32, posX=130, posY=54, posZ=2, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=39, worldY=32, posX=127, posY=183, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=39, worldY=32, posX=104, posY=179, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=39, worldY=32, posX=127, posY=183, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=39, worldY=32, posX=199, posY=220, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=35, worldY=34, posX=134, posY=208, town="Muldraugh", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=26, worldY=39, posX=251, posY=48, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=183, posY=130, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=196, posY=127, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=187, posY=147, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=181, posY=240, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=196, posY=225, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=188, posY=215, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=24, worldY=27, posX=53, posY=278, town="Fallas Lake", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=20, worldY=17, posX=82, posY=158, town="Riverside", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=18, worldY=32, posX=76, posY=114, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=32, posX=71, posY=80, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=32, posX=71, posY=68, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=32, posX=70, posY=58, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=32, posX=39, posY=83, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=31, posX=67, posY=285, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=31, posX=63, posY=279, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=31, posX=59, posY=269, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=31, posX=97, posY=286, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=31, posX=103, posY=280, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=31, posX=100, posY=266, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=12, worldY=28, posX=201, posY=153, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=12, worldY=28, posX=208, posY=114, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=12, worldY=28, posX=92, posY=98, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=12, worldY=28, posX=104, posY=69, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=12, worldY=28, posX=103, posY=62, town="Doe Valley Forest", type="NonResidential", cat="Business", hardcore=true, majorTown=false, balance=false, },
        { worldX=12, worldY=28, posX=46, posY=166, town="Doe Valley Forest", type="Residential", cat="Home", hardcore=true, majorTown=false, balance=false, },
        { worldX=25, worldY=39, posX=183, posY=210, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=183, posY=231, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=183, posY=234, posZ=1, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=25, worldY=39, posX=197, posY=234, posZ=1, town="Rosewood", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=40, worldY=12, posX=232, posY=33, town="Louisville", type="Residential", cat="Home", hardcore=true, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=130, posY=101, town="Louisville", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=41, worldY=5, posX=114, posY=89, town="Louisville", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=43, worldY=4, posX=55, posY=190, town="Louisville", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=13, worldY=21, posX=243, posY=108, town="Doe Valley Forest", type="NonResidential", cat="Civic", hardcore=true, majorTown=false, balance=false, },
        { worldX=13, worldY=21, posX=204, posY=108, town="Doe Valley Forest", type="NonResidential", cat="Civic", hardcore=true, majorTown=false, balance=false, },
        { worldX=13, worldY=21, posX=208, posY=185, town="Doe Valley Forest", type="NonResidential", cat="Civic", hardcore=true, majorTown=false, balance=false, },
        { worldX=13, worldY=21, posX=180, posY=216, posZ=2, town="Doe Valley Forest", type="NonResidential", cat="Civic", hardcore=true, majorTown=false, balance=false, },
        { worldX=13, worldY=21, posX=186, posY=227, town="Doe Valley Forest", type="NonResidential", cat="Civic", hardcore=true, majorTown=false, balance=false, },
        { worldX=13, worldY=21, posX=210, posY=224, town="Doe Valley Forest", type="NonResidential", cat="Civic", hardcore=true, majorTown=false, balance=false, },
        { worldX=6, worldY=19, posX=231, posY=277, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=6, worldY=20, posX=153, posY=142, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=7, worldY=21, posX=136, posY=104, posZ=-2, town="Brandenburg", type="NonResidential", cat="Business", hardcore=true, majorTown=true, balance=false, },
        { worldX=6, worldY=28, posX=179, posY=201, town="Ekron", type="Residential", cat="Home", hardcore=true, majorTown=true, balance=false, },
        { worldX=9, worldY=30, posX=191, posY=52, posZ=1, town="Doe Valley Forest", type="NonResidential", cat="Civic", hardcore=true, majorTown=false, balance=false, },
        { worldX=9, worldY=30, posX=187, posY=92, posZ=1, town="Doe Valley Forest", type="NonResidential", cat="Civic", hardcore=true, majorTown=false, balance=false, },
        { worldX=11, worldY=32, posX=71, posY=88, town="Doe Valley Forest", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=7, worldY=37, posX=66, posY=118, town="Echo Creek", type="Residential", cat="Cabin", hardcore=true, majorTown=true, balance=false, },
        { worldX=8, worldY=36, posX=164, posY=95, posZ=1, town="Echo Creek", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=8, worldY=46, posX=89, posY=136, posZ=1, town="Irvington", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
        { worldX=19, worldY=48, posX=15, posY=160, town="Hog Wallow", type="Residential", cat="Cabin", hardcore=true, majorTown=false, balance=false, },
        { worldX=26, worldY=48, posX=83, posY=222, town="Hog Wallow", type="Residential", cat="Cabin", hardcore=true, majorTown=false, balance=false, },
        { worldX=27, worldY=49, posX=17, posY=203, town="Hog Wallow", type="Residential", cat="Cabin", hardcore=true, majorTown=false, balance=false, },
        { worldX=26, worldY=50, posX=215, posY=285, town="Hog Wallow", type="NonResidential", cat="Industrial", hardcore=true, majorTown=false, balance=false, },
        { worldX=28, worldY=50, posX=241, posY=53, posZ=1, town="Hog Wallow", type="Residential", cat="Cabin", hardcore=true, majorTown=false, balance=false, },
        { worldX=28, worldY=50, posX=259, posY=262, town="Hog Wallow", type="Residential", cat="Cabin", hardcore=true, majorTown=false, balance=false, },
        { worldX=18, worldY=31, posX=176, posY=65, posZ=-1, town="Doe Valley Forest", type="Residential", cat="Home", hardcore=true, majorTown=false, balance=false, },
        { worldX=12, worldY=41, posX=219, posY=239, town="Echo Creek", type="Residential", cat="Cabin", hardcore=true, majorTown=true, balance=false, },
        { worldX=34, worldY=29, posX=53, posY=34, town="Muldraugh", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=21, worldY=25, posX=67, posY=120, posZ=2, town="Fallas Lake", type="Residential", cat="Cabin", hardcore=true, majorTown=true, balance=false, },
        { worldX=33, worldY=27, posX=186, posY=161, posZ=1, town="Muldraugh", type="NonResidential", cat="Farm", hardcore=true, majorTown=true, balance=false, },
        { worldX=16, worldY=20, posX=33, posY=279, town="Riverside", type="NonResidential", cat="Industrial", hardcore=true, majorTown=true, balance=false, },
        { worldX=42, worldY=29, posX=115, posY=47, town="Muldraugh", type="Residential", cat="Cabin", hardcore=true, majorTown=true, balance=false, },
        { worldX=4, worldY=19, posX=179, posY=158, town="Brandenburg", type="NonResidential", cat="Civic", hardcore=true, majorTown=true, balance=false, },
    }
    return points
end
