function RSL_SpawnPoints_Indiana_NewMiddletown()
    local points = {
        { worldX=19, worldY=5, posX=230, posY=245, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=5, posX=66, posY=284, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=5, posX=137, posY=184, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=5, posX=139, posY=104, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=6, posX=79, posY=84, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=6, posX=101, posY=209, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=6, posX=168, posY=271, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=6, posX=263, posY=261, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=6, posX=264, posY=180, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=6, posX=266, posY=59, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=6, posX=277, posY=136, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=21, worldY=6, posX=279, posY=216, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=7, posY=224, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=8, posY=27, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=10, posY=186, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=13, posY=73, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=13, posY=131, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=45, posY=211, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=52, posY=74, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=52, posY=158, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=53, posY=28, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=58, posY=117, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=77, posY=108, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=80, posY=162, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=86, posY=240, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=105, posY=158, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=106, posY=128, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=133, posY=158, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=140, posY=110, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=146, posY=224, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=152, posY=262, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=167, posY=226, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=170, posY=172, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=176, posY=295, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=188, posY=258, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=190, posY=269, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=197, posY=228, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=210, posY=266, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=212, posY=295, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=237, posY=291, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=251, posY=231, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=255, posY=263, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
        { worldX=22, worldY=6, posX=288, posY=266, town="New Middletown, IN", type="NonResidential", cat="Civic", hardcore=false, majorTown=false, balance=false, },
    }
    return points
end
